// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionMetadata{
	"rhysd/action-setup-vim@v1.3.2": {
		Name: "Setup Vim",
		Inputs: ActionMetadataInputs{
			"configure-args": {"configure-args", false, false, ""},
			"neovim":         {"neovim", false, false, ""},
			"token":          {"token", false, false, ""},
			"version":        {"version", false, false, ""},
		},
		Outputs: ActionMetadataOutputs{
			"executable": {"executable"},
		},
	},
	"rhysd/changelog-from-release/action@v2.2.2": {
		Name: "Run changelog-from-release",
		Inputs: ActionMetadataInputs{
			"commit":       {"commit", false, false, ""},
			"file":         {"file", true, false, ""},
			"github_token": {"github_token", true, false, ""},
			"push":         {"push", false, false, ""},
			"version":      {"version", false, false, ""},
		},
	},
}

// OutdatedPopularActionSpecs is a spec set of known outdated popular actions. The word 'outdated'
// means that the runner used by the action is no longer available such as "node12", "node16".
var OutdatedPopularActionSpecs = map[string]struct{}{}
