#!/bin/bash

set -e -o pipefail

if [[ "$CI" != "" ]]; then
    exit
fi

set -x

make build SKIP_GO_GENERATE=true
make test SKIP_GO_GENERATE=true
make lint SKIP_GO_GENERATE=true

if [ -x ./actionlint ]; then
    ./actionlint
fi
