// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

func addressOfString(s string) *string {
	return &s // Go does not allow get pointer of string literal
}

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionSpec{
	"8398a7/action-slack@v1": {
		Name: "action-slack",
		Inputs: map[string]*ActionInput{
			"failedMention": {
				Default: addressOfString("here"),
			},
			"payload": {},
			"text":    {},
			"type":    {},
		},
	},
	"8398a7/action-slack@v2": {
		Name: "action-slack",
		Inputs: map[string]*ActionInput{
			"author_name": {
				Default: addressOfString("8398a7@action-slack"),
			},
			"channel": {
				Default: addressOfString(""),
			},
			"icon_emoji": {
				Default: addressOfString(""),
			},
			"icon_url": {
				Default: addressOfString(""),
			},
			"mention": {
				Default: addressOfString(""),
			},
			"only_mention_fail": {
				Default: addressOfString(""),
			},
			"payload": {},
			"status":  {},
			"text": {
				Default: addressOfString(""),
			},
			"username": {
				Default: addressOfString(""),
			},
		},
	},
	"8398a7/action-slack@v3": {
		Name: "action-slack",
		Inputs: map[string]*ActionInput{
			"author_name": {
				Default: addressOfString("8398a7@action-slack"),
			},
			"channel": {
				Default: addressOfString(""),
			},
			"custom_payload": {},
			"fields": {
				Default: addressOfString(""),
			},
			"github_base_url": {
				Default: addressOfString(""),
			},
			"github_token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"icon_emoji": {
				Default: addressOfString(""),
			},
			"icon_url": {
				Default: addressOfString(""),
			},
			"if_mention": {
				Default: addressOfString(""),
			},
			"job_name": {
				Default: addressOfString(""),
			},
			"mention": {
				Default: addressOfString(""),
			},
			"status": {
				Required: true,
			},
			"text": {
				Default: addressOfString(""),
			},
			"username": {
				Default: addressOfString(""),
			},
		},
	},
	"Azure/container-scan@v0": {
		Name: "Container image scan",
		Inputs: map[string]*ActionInput{
			"image-name": {
				Required: true,
			},
			"password": {},
			"run-quality-checks": {
				Default: addressOfString("true"),
			},
			"severity-threshold": {
				Default: addressOfString("HIGH"),
			},
			"token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"username": {},
		},
		Outputs: map[string]struct{}{
			"check-run-url":    {},
			"scan-report-path": {},
		},
	},
	"EnricoMi/publish-unit-test-result-action@v1": {
		Name: "Publish Unit Test Results",
		Inputs: map[string]*ActionInput{
			"check_name": {
				Default: addressOfString("Unit Test Results"),
			},
			"check_run_annotations": {
				Default: addressOfString("all tests, skipped tests"),
			},
			"check_run_annotations_branch": {},
			"comment_mode": {
				Default: addressOfString("update last"),
			},
			"comment_on_pr": {},
			"comment_title": {},
			"commit":        {},
			"compare_to_earlier_commit": {
				Default: addressOfString("true"),
			},
			"deduplicate_classes_by_file_name": {},
			"fail_on": {
				Default: addressOfString("test failures"),
			},
			"files": {
				Required: true,
			},
			"github_retries": {
				Default: addressOfString("10"),
			},
			"github_token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"hide_comments": {
				Default: addressOfString("all but latest"),
			},
			"pull_request_build": {
				Default: addressOfString("merge"),
			},
			"report_individual_runs": {},
			"seconds_between_github_reads": {
				Default: addressOfString("0.25"),
			},
			"seconds_between_github_writes": {
				Default: addressOfString("2.0"),
			},
			"test_changes_limit": {},
		},
	},
	"JamesIves/github-pages-deploy-action@releases/v3": {
		Name: "Deploy to GitHub Pages",
		Inputs: map[string]*ActionInput{
			"ACCESS_TOKEN": {},
			"BASE_BRANCH":  {},
			"BRANCH": {
				Required: true,
			},
			"CLEAN": {
				Default: addressOfString("true"),
			},
			"CLEAN_EXCLUDE":  {},
			"COMMIT_MESSAGE": {},
			"FOLDER": {
				Required: true,
			},
			"GITHUB_TOKEN":     {},
			"GIT_CONFIG_EMAIL": {},
			"GIT_CONFIG_NAME":  {},
			"LFS":              {},
			"PRESERVE":         {},
			"REPOSITORY_NAME":  {},
			"SILENT":           {},
			"SINGLE_COMMIT":    {},
			"SSH":              {},
			"TARGET_FOLDER":    {},
			"WORKSPACE":        {},
		},
		Outputs: map[string]struct{}{
			"DEPLOYMENT_STATUS": {},
		},
	},
	"JamesIves/github-pages-deploy-action@releases/v4": {
		Name: "Deploy to GitHub Pages",
		Inputs: map[string]*ActionInput{
			"branch": {
				Required: true,
			},
			"clean": {
				Default: addressOfString("true"),
			},
			"clean-exclude":  {},
			"commit-message": {},
			"dry-run":        {},
			"folder": {
				Required: true,
			},
			"git-config-email": {},
			"git-config-name":  {},
			"repository-name":  {},
			"silent":           {},
			"single-commit":    {},
			"ssh-key":          {},
			"target-folder":    {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"workspace": {},
		},
		Outputs: map[string]struct{}{
			"deployment-status": {},
		},
	},
	"ReactiveCircus/android-emulator-runner@v1": {
		Name: "Android Emulator Runner",
		Inputs: map[string]*ActionInput{
			"api-level": {
				Required: true,
			},
			"arch": {
				Default: addressOfString("x86"),
			},
			"disable-animations": {
				Default: addressOfString("true"),
			},
			"headless": {
				Default: addressOfString("true"),
			},
			"profile": {},
			"script": {
				Required: true,
			},
			"target": {
				Default: addressOfString("default"),
			},
		},
	},
	"ReactiveCircus/android-emulator-runner@v2": {
		Name: "Android Emulator Runner",
		Inputs: map[string]*ActionInput{
			"api-level": {
				Required: true,
			},
			"arch": {
				Default: addressOfString("x86"),
			},
			"avd-name": {
				Default: addressOfString("test"),
			},
			"cmake": {},
			"cores": {
				Default: addressOfString("2"),
			},
			"disable-animations": {
				Default: addressOfString("true"),
			},
			"disable-linux-hw-accel": {
				Default: addressOfString("true"),
			},
			"disable-spellchecker": {
				Default: addressOfString("false"),
			},
			"emulator-build": {},
			"emulator-options": {
				Default: addressOfString("-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"),
			},
			"force-avd-creation": {
				Default: addressOfString("true"),
			},
			"ndk":      {},
			"profile":  {},
			"ram-size": {},
			"script": {
				Required: true,
			},
			"sdcard-path-or-size": {},
			"target": {
				Default: addressOfString("default"),
			},
			"working-directory": {},
		},
	},
	"actions-cool/issues-helper@v1": {
		Name: "Issues Helper",
		Inputs: map[string]*ActionInput{
			"actions":         {},
			"assignees":       {},
			"body":            {},
			"body-includes":   {},
			"comment-auth":    {},
			"comment-id":      {},
			"contents":        {},
			"direction":       {},
			"inactive-day":    {},
			"inactive-label":  {},
			"issue-assignee":  {},
			"issue-creator":   {},
			"issue-mentioned": {},
			"issue-number":    {},
			"issue-state":     {},
			"labels":          {},
			"state":           {},
			"title":           {},
			"title-includes":  {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"update-mode": {},
		},
		Outputs: map[string]struct{}{
			"comment-id":   {},
			"comments":     {},
			"issue-number": {},
		},
	},
	"actions-cool/issues-helper@v2": {
		Name: "Issues Helper",
		Inputs: map[string]*ActionInput{
			"actions":            {},
			"assignee-includes":  {},
			"assignees":          {},
			"body":               {},
			"body-includes":      {},
			"close-issue":        {},
			"comment-auth":       {},
			"comment-id":         {},
			"contents":           {},
			"count-comments":     {},
			"count-lables":       {},
			"direction":          {},
			"duplicate-command":  {},
			"duplicate-labels":   {},
			"inactive-day":       {},
			"inactive-label":     {},
			"issue-assignee":     {},
			"issue-contents":     {},
			"issue-creator":      {},
			"issue-mentioned":    {},
			"issue-number":       {},
			"issue-state":        {},
			"labels":             {},
			"lock-reason":        {},
			"random-to":          {},
			"remove-labels":      {},
			"require-permission": {},
			"state":              {},
			"title":              {},
			"title-includes":     {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"update-mode": {},
		},
		Outputs: map[string]struct{}{
			"check-result": {},
			"comment-id":   {},
			"comments":     {},
			"issue-number": {},
		},
	},
	"actions-rs/audit-check@v1": {
		Name: "rust-audit-check",
		Inputs: map[string]*ActionInput{
			"token": {
				Required: true,
			},
		},
	},
	"actions-rs/cargo@v1": {
		Name: "rust-cargo",
		Inputs: map[string]*ActionInput{
			"args": {},
			"command": {
				Required: true,
			},
			"toolchain": {},
			"use-cross": {
				Default: addressOfString("false"),
			},
		},
	},
	"actions-rs/clippy-check@v1": {
		Name: "rust-clippy-check",
		Inputs: map[string]*ActionInput{
			"args": {},
			"name": {
				Default: addressOfString("clippy"),
			},
			"token": {
				Required: true,
			},
			"toolchain": {},
			"use-cross": {
				Default: addressOfString("false"),
			},
		},
	},
	"actions-rs/toolchain@v1": {
		Name: "rust-toolchain",
		Inputs: map[string]*ActionInput{
			"components": {},
			"default": {
				Default: addressOfString("false"),
			},
			"override": {
				Default: addressOfString("false"),
			},
			"profile":   {},
			"target":    {},
			"toolchain": {},
		},
		Outputs: map[string]struct{}{
			"cargo":      {},
			"rustc":      {},
			"rustc_hash": {},
			"rustup":     {},
		},
	},
	"actions/cache@v1": {
		Name: "Cache",
		Inputs: map[string]*ActionInput{
			"key": {
				Required: true,
			},
			"path": {
				Required: true,
			},
			"restore-keys": {},
		},
		Outputs: map[string]struct{}{
			"cache-hit": {},
		},
	},
	"actions/cache@v2": {
		Name: "Cache",
		Inputs: map[string]*ActionInput{
			"key": {
				Required: true,
			},
			"path": {
				Required: true,
			},
			"restore-keys":      {},
			"upload-chunk-size": {},
		},
		Outputs: map[string]struct{}{
			"cache-hit": {},
		},
	},
	"actions/checkout@v1": {
		Name: "Checkout",
		Inputs: map[string]*ActionInput{
			"clean": {
				Default: addressOfString("true"),
			},
			"fetch-depth": {},
			"lfs":         {},
			"path":        {},
			"ref":         {},
			"repository":  {},
			"submodules":  {},
			"token":       {},
		},
	},
	"actions/checkout@v2": {
		Name: "Checkout",
		Inputs: map[string]*ActionInput{
			"clean": {
				Default: addressOfString("true"),
			},
			"fetch-depth": {
				Default: addressOfString("1"),
			},
			"lfs": {
				Default: addressOfString("false"),
			},
			"path": {},
			"persist-credentials": {
				Default: addressOfString("true"),
			},
			"ref": {},
			"repository": {
				Default: addressOfString("${{ github.repository }}"),
			},
			"ssh-key":         {},
			"ssh-known-hosts": {},
			"ssh-strict": {
				Default: addressOfString("true"),
			},
			"submodules": {
				Default: addressOfString("false"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"actions/delete-package-versions@v1": {
		Name: "Delete Package Versions",
		Inputs: map[string]*ActionInput{
			"num-old-versions-to-delete": {
				Default: addressOfString("1"),
			},
			"owner":               {},
			"package-name":        {},
			"package-version-ids": {},
			"repo":                {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"actions/download-artifact@v1": {
		Name: "Download a Build Artifact",
		Inputs: map[string]*ActionInput{
			"name": {
				Required: true,
			},
			"path": {},
		},
	},
	"actions/download-artifact@v2": {
		Name: "Download a Build Artifact",
		Inputs: map[string]*ActionInput{
			"name": {},
			"path": {},
		},
	},
	"actions/first-interaction@v1": {
		Name: "First interaction",
		Inputs: map[string]*ActionInput{
			"issue-message": {},
			"pr-message":    {},
			"repo-token": {
				Required: true,
			},
		},
	},
	"actions/github-script@v1": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionInput{
			"debug": {
				Default: addressOfString("false"),
			},
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"previews": {},
			"result-encoding": {
				Default: addressOfString("json"),
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: addressOfString("actions/github-script"),
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v2": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionInput{
			"debug": {
				Default: addressOfString("false"),
			},
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"previews": {},
			"result-encoding": {
				Default: addressOfString("json"),
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: addressOfString("actions/github-script"),
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v3": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionInput{
			"debug": {
				Default: addressOfString("false"),
			},
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"previews": {},
			"result-encoding": {
				Default: addressOfString("json"),
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: addressOfString("actions/github-script"),
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v4": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionInput{
			"debug": {
				Default: addressOfString("false"),
			},
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"previews": {},
			"result-encoding": {
				Default: addressOfString("json"),
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: addressOfString("actions/github-script"),
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/labeler@v2": {
		Name: "Pull Request Labeler",
		Inputs: map[string]*ActionInput{
			"configuration-path": {
				Default: addressOfString(".github/labeler.yml"),
			},
			"repo-token": {},
			"sync-labels": {
				Default: addressOfString("false"),
			},
		},
	},
	"actions/labeler@v3": {
		Name: "Labeler",
		Inputs: map[string]*ActionInput{
			"configuration-path": {
				Default: addressOfString(".github/labeler.yml"),
			},
			"repo-token": {},
			"sync-labels": {
				Default: addressOfString("false"),
			},
		},
	},
	"actions/setup-dotnet@v1": {
		Name: "Setup .NET Core SDK",
		Inputs: map[string]*ActionInput{
			"config-file":        {},
			"dotnet-version":     {},
			"include-prerelease": {},
			"owner":              {},
			"source-url":         {},
		},
	},
	"actions/setup-go@v1": {
		Name: "Setup Go environment",
		Inputs: map[string]*ActionInput{
			"go-version": {
				Default: addressOfString("1.10"),
			},
			"version": {},
		},
	},
	"actions/setup-go@v2": {
		Name: "Setup Go environment",
		Inputs: map[string]*ActionInput{
			"go-version": {},
			"stable": {
				Default: addressOfString("true"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"actions/setup-java@v1": {
		Name: "Setup Java JDK",
		Inputs: map[string]*ActionInput{
			"architecture": {
				Default: addressOfString("x64"),
			},
			"gpg-passphrase":  {},
			"gpg-private-key": {},
			"java-package": {
				Default: addressOfString("jdk"),
			},
			"java-version": {
				Required: true,
			},
			"jdkFile": {},
			"server-id": {
				Default: addressOfString("github"),
			},
			"server-password": {
				Default: addressOfString("GITHUB_TOKEN"),
			},
			"server-username": {
				Default: addressOfString("GITHUB_ACTOR"),
			},
			"settings-path": {},
		},
		Outputs: map[string]struct{}{
			"path":    {},
			"version": {},
		},
	},
	"actions/setup-java@v2": {
		Name: "Setup Java JDK",
		Inputs: map[string]*ActionInput{
			"architecture": {
				Default: addressOfString("x64"),
			},
			"check-latest": {
				Default: addressOfString("false"),
			},
			"distribution": {
				Required: true,
			},
			"gpg-passphrase":  {},
			"gpg-private-key": {},
			"java-package": {
				Default: addressOfString("jdk"),
			},
			"java-version": {
				Required: true,
			},
			"jdkFile": {},
			"overwrite-settings": {
				Default: addressOfString("true"),
			},
			"server-id": {
				Default: addressOfString("github"),
			},
			"server-password": {
				Default: addressOfString("GITHUB_TOKEN"),
			},
			"server-username": {
				Default: addressOfString("GITHUB_ACTOR"),
			},
			"settings-path": {},
		},
		Outputs: map[string]struct{}{
			"distribution": {},
			"path":         {},
			"version":      {},
		},
	},
	"actions/setup-node@v1": {
		Name: "Setup Node.js environment",
		Inputs: map[string]*ActionInput{
			"always-auth": {
				Default: addressOfString("false"),
			},
			"node-version": {
				Default: addressOfString("10.x"),
			},
			"registry-url": {},
			"scope":        {},
			"version":      {},
		},
	},
	"actions/setup-node@v2": {
		Name: "Setup Node.js environment",
		Inputs: map[string]*ActionInput{
			"always-auth": {
				Default: addressOfString("false"),
			},
			"architecture": {},
			"cache":        {},
			"check-latest": {
				Default: addressOfString("false"),
			},
			"node-version": {},
			"registry-url": {},
			"scope":        {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"version": {},
		},
	},
	"actions/setup-python@v1": {
		Name: "Setup Python",
		Inputs: map[string]*ActionInput{
			"architecture": {
				Default: addressOfString("x64"),
			},
			"python-version": {
				Default: addressOfString("3.x"),
			},
		},
		Outputs: map[string]struct{}{
			"python-version": {},
		},
	},
	"actions/setup-python@v2": {
		Name: "Setup Python",
		Inputs: map[string]*ActionInput{
			"architecture": {},
			"python-version": {
				Default: addressOfString("3.x"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
		Outputs: map[string]struct{}{
			"python-version": {},
		},
	},
	"actions/stale@v1": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionInput{
			"days-before-close": {
				Default: addressOfString("7"),
			},
			"days-before-stale": {
				Default: addressOfString("60"),
			},
			"exempt-issue-label": {},
			"exempt-pr-label":    {},
			"operations-per-run": {
				Default: addressOfString("30"),
			},
			"repo-token": {
				Required: true,
			},
			"stale-issue-label": {
				Default: addressOfString("Stale"),
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: addressOfString("Stale"),
			},
			"stale-pr-message": {},
		},
	},
	"actions/stale@v2": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionInput{
			"days-before-close": {
				Default: addressOfString("7"),
			},
			"days-before-stale": {
				Default: addressOfString("60"),
			},
			"debug-only": {
				Default: addressOfString("false"),
			},
			"exempt-issue-labels": {
				Default: addressOfString(""),
			},
			"exempt-pr-labels": {
				Default: addressOfString(""),
			},
			"only-labels": {
				Default: addressOfString(""),
			},
			"operations-per-run": {
				Default: addressOfString("30"),
			},
			"repo-token": {
				Required: true,
			},
			"stale-issue-label": {
				Default: addressOfString("Stale"),
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: addressOfString("Stale"),
			},
			"stale-pr-message": {},
		},
	},
	"actions/stale@v3": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionInput{
			"any-of-issue-labels": {
				Default: addressOfString(""),
			},
			"any-of-labels": {
				Default: addressOfString(""),
			},
			"any-of-pr-labels": {
				Default: addressOfString(""),
			},
			"ascending": {
				Default: addressOfString("false"),
			},
			"close-issue-label":   {},
			"close-issue-message": {},
			"close-pr-label":      {},
			"close-pr-message":    {},
			"days-before-close": {
				Default: addressOfString("7"),
			},
			"days-before-issue-close": {},
			"days-before-issue-stale": {},
			"days-before-pr-close":    {},
			"days-before-pr-stale":    {},
			"days-before-stale": {
				Default: addressOfString("60"),
			},
			"debug-only": {
				Default: addressOfString("false"),
			},
			"delete-branch": {
				Default: addressOfString("false"),
			},
			"enable-statistics": {
				Default: addressOfString("true"),
			},
			"exempt-all-assignees": {
				Default: addressOfString("false"),
			},
			"exempt-all-issue-assignees": {
				Default: addressOfString(""),
			},
			"exempt-all-issue-milestones": {
				Default: addressOfString(""),
			},
			"exempt-all-milestones": {
				Default: addressOfString("false"),
			},
			"exempt-all-pr-assignees": {
				Default: addressOfString(""),
			},
			"exempt-all-pr-milestones": {
				Default: addressOfString(""),
			},
			"exempt-assignees": {
				Default: addressOfString(""),
			},
			"exempt-issue-assignees": {
				Default: addressOfString(""),
			},
			"exempt-issue-labels": {
				Default: addressOfString(""),
			},
			"exempt-issue-milestones": {
				Default: addressOfString(""),
			},
			"exempt-milestones": {
				Default: addressOfString(""),
			},
			"exempt-pr-assignees": {
				Default: addressOfString(""),
			},
			"exempt-pr-labels": {
				Default: addressOfString(""),
			},
			"exempt-pr-milestones": {
				Default: addressOfString(""),
			},
			"only-issue-labels": {
				Default: addressOfString(""),
			},
			"only-labels": {
				Default: addressOfString(""),
			},
			"only-pr-labels": {
				Default: addressOfString(""),
			},
			"operations-per-run": {
				Default: addressOfString("30"),
			},
			"remove-issue-stale-when-updated": {
				Default: addressOfString("true"),
			},
			"remove-pr-stale-when-updated": {
				Default: addressOfString("true"),
			},
			"remove-stale-when-updated": {
				Default: addressOfString("true"),
			},
			"repo-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"skip-stale-issue-message": {
				Default: addressOfString("false"),
			},
			"skip-stale-pr-message": {
				Default: addressOfString("false"),
			},
			"stale-issue-label": {
				Default: addressOfString("Stale"),
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: addressOfString("Stale"),
			},
			"stale-pr-message": {},
			"start-date": {
				Default: addressOfString(""),
			},
		},
	},
	"actions/stale@v4": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionInput{
			"any-of-issue-labels": {
				Default: addressOfString(""),
			},
			"any-of-labels": {
				Default: addressOfString(""),
			},
			"any-of-pr-labels": {
				Default: addressOfString(""),
			},
			"ascending": {
				Default: addressOfString("false"),
			},
			"close-issue-label":   {},
			"close-issue-message": {},
			"close-pr-label":      {},
			"close-pr-message":    {},
			"days-before-close": {
				Default: addressOfString("7"),
			},
			"days-before-issue-close": {},
			"days-before-issue-stale": {},
			"days-before-pr-close":    {},
			"days-before-pr-stale":    {},
			"days-before-stale": {
				Default: addressOfString("60"),
			},
			"debug-only": {
				Default: addressOfString("false"),
			},
			"delete-branch": {
				Default: addressOfString("false"),
			},
			"enable-statistics": {
				Default: addressOfString("true"),
			},
			"exempt-all-assignees": {
				Default: addressOfString("false"),
			},
			"exempt-all-issue-assignees": {
				Default: addressOfString(""),
			},
			"exempt-all-issue-milestones": {
				Default: addressOfString(""),
			},
			"exempt-all-milestones": {
				Default: addressOfString("false"),
			},
			"exempt-all-pr-assignees": {
				Default: addressOfString(""),
			},
			"exempt-all-pr-milestones": {
				Default: addressOfString(""),
			},
			"exempt-assignees": {
				Default: addressOfString(""),
			},
			"exempt-issue-assignees": {
				Default: addressOfString(""),
			},
			"exempt-issue-labels": {
				Default: addressOfString(""),
			},
			"exempt-issue-milestones": {
				Default: addressOfString(""),
			},
			"exempt-milestones": {
				Default: addressOfString(""),
			},
			"exempt-pr-assignees": {
				Default: addressOfString(""),
			},
			"exempt-pr-labels": {
				Default: addressOfString(""),
			},
			"exempt-pr-milestones": {
				Default: addressOfString(""),
			},
			"only-issue-labels": {
				Default: addressOfString(""),
			},
			"only-labels": {
				Default: addressOfString(""),
			},
			"only-pr-labels": {
				Default: addressOfString(""),
			},
			"operations-per-run": {
				Default: addressOfString("30"),
			},
			"remove-issue-stale-when-updated": {
				Default: addressOfString(""),
			},
			"remove-pr-stale-when-updated": {
				Default: addressOfString(""),
			},
			"remove-stale-when-updated": {
				Default: addressOfString("true"),
			},
			"repo-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"stale-issue-label": {
				Default: addressOfString("Stale"),
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: addressOfString("Stale"),
			},
			"stale-pr-message": {},
			"start-date": {
				Default: addressOfString(""),
			},
		},
		Outputs: map[string]struct{}{
			"closed-issues-prs": {},
			"staled-issues-prs": {},
		},
	},
	"actions/upload-artifact@v1": {
		Name: "Upload a Build Artifact",
		Inputs: map[string]*ActionInput{
			"name": {
				Required: true,
			},
			"path": {
				Required: true,
			},
		},
	},
	"actions/upload-artifact@v2": {
		Name: "Upload a Build Artifact",
		Inputs: map[string]*ActionInput{
			"if-no-files-found": {
				Default: addressOfString("warn"),
			},
			"name": {
				Default: addressOfString("artifact"),
			},
			"path": {
				Required: true,
			},
			"retention-days": {},
		},
	},
	"aws-actions/configure-aws-credentials@v1": {
		Name: "\"Configure AWS Credentials\" Action For GitHub Actions",
		Inputs: map[string]*ActionInput{
			"aws-access-key-id": {},
			"aws-region": {
				Required: true,
			},
			"aws-secret-access-key":     {},
			"aws-session-token":         {},
			"mask-aws-account-id":       {},
			"role-duration-seconds":     {},
			"role-external-id":          {},
			"role-session-name":         {},
			"role-skip-session-tagging": {},
			"role-to-assume":            {},
		},
		Outputs: map[string]struct{}{
			"aws-account-id": {},
		},
	},
	"azure/aks-set-context@v1": {
		Name: "Azure Kubernetes set context",
		Inputs: map[string]*ActionInput{
			"cluster-name": {
				Default: addressOfString(""),
			},
			"creds": {
				Required: true,
				Default:  addressOfString(""),
			},
			"resource-group": {
				Default: addressOfString(""),
			},
		},
	},
	"azure/login@v1": {
		Name: "Azure Login",
		Inputs: map[string]*ActionInput{
			"allow-no-subscriptions": {
				Default: addressOfString("false"),
			},
			"creds": {
				Required: true,
			},
			"enable-AzPSSession": {
				Default: addressOfString("false"),
			},
			"environment": {
				Default: addressOfString("azurecloud"),
			},
		},
	},
	"bahmutov/npm-install@v1": {
		Name: "NPM or Yarn install with caching",
		Inputs: map[string]*ActionInput{
			"install-command":   {},
			"useLockFile":       {},
			"useRollingCache":   {},
			"working-directory": {},
		},
	},
	"codecov/codecov-action@v1": {
		Name: "Codecov",
		Inputs: map[string]*ActionInput{
			"aws_curl_args":          {},
			"codecov_curl_args":      {},
			"commit_parent":          {},
			"directory":              {},
			"env_vars":               {},
			"fail_ci_if_error":       {},
			"file":                   {},
			"files":                  {},
			"flags":                  {},
			"functionalities":        {},
			"gcov_args":              {},
			"gcov_executable":        {},
			"gcov_path_exclude":      {},
			"gcov_path_include":      {},
			"gcov_prefix":            {},
			"gcov_root_dir":          {},
			"move_coverage_to_trash": {},
			"name":                   {},
			"network_filter":         {},
			"override_branch":        {},
			"override_build":         {},
			"override_commit":        {},
			"override_pr":            {},
			"override_tag":           {},
			"path_to_write_report":   {},
			"root_dir":               {},
			"token":                  {},
			"verbose":                {},
			"working-directory":      {},
			"xcode_derived_data":     {},
			"xcode_package":          {},
		},
	},
	"codecov/codecov-action@v2": {
		Name: "Codecov",
		Inputs: map[string]*ActionInput{
			"commit_parent":          {},
			"directory":              {},
			"dry_run":                {},
			"env_vars":               {},
			"fail_ci_if_error":       {},
			"file":                   {},
			"files":                  {},
			"flags":                  {},
			"functionalities":        {},
			"move_coverage_to_trash": {},
			"name":                   {},
			"override_branch":        {},
			"override_build":         {},
			"override_commit":        {},
			"override_pr":            {},
			"override_tag":           {},
			"root_dir":               {},
			"slug":                   {},
			"token":                  {},
			"url":                    {},
			"verbose":                {},
			"working-directory":      {},
		},
	},
	"dawidd6/action-download-artifact@v2": {
		Name: "Download workflow artifact",
		Inputs: map[string]*ActionInput{
			"branch": {},
			"commit": {},
			"event":  {},
			"github_token": {
				Default: addressOfString("${{github.token}}"),
			},
			"name": {},
			"path": {
				Default: addressOfString("./"),
			},
			"pr": {},
			"repo": {
				Default: addressOfString("${{github.repository}}"),
			},
			"run_id":     {},
			"run_number": {},
			"workflow": {
				Required: true,
			},
			"workflow_conclusion": {
				Default: addressOfString("completed,success"),
			},
		},
	},
	"dawidd6/action-send-mail@v1": {
		Name: "Send email",
		Inputs: map[string]*ActionInput{
			"body": {
				Required: true,
			},
			"content_type": {
				Default: addressOfString("text/plain"),
			},
			"from": {
				Required: true,
			},
			"password": {
				Required: true,
			},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {
				Required: true,
			},
		},
	},
	"dawidd6/action-send-mail@v2": {
		Name: "Send email",
		Inputs: map[string]*ActionInput{
			"attachments": {},
			"bcc":         {},
			"body": {
				Required: true,
			},
			"cc": {},
			"content_type": {
				Default: addressOfString("text/plain"),
			},
			"convert_markdown": {},
			"from": {
				Required: true,
			},
			"ignore_cert": {},
			"password": {
				Required: true,
			},
			"reply_to": {},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {
				Required: true,
			},
		},
	},
	"dawidd6/action-send-mail@v3": {
		Name: "Send email",
		Inputs: map[string]*ActionInput{
			"attachments":      {},
			"bcc":              {},
			"body":             {},
			"cc":               {},
			"convert_markdown": {},
			"from": {
				Required: true,
			},
			"html_body":   {},
			"ignore_cert": {},
			"password":    {},
			"priority":    {},
			"reply_to":    {},
			"secure":      {},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {},
		},
	},
	"dessant/lock-threads@v2": {
		Name: "Lock Threads",
		Inputs: map[string]*ActionInput{
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"issue-exclude-created-before": {
				Default: addressOfString(""),
			},
			"issue-exclude-labels": {
				Default: addressOfString(""),
			},
			"issue-lock-comment": {
				Default: addressOfString(""),
			},
			"issue-lock-inactive-days": {
				Default: addressOfString("365"),
			},
			"issue-lock-labels": {
				Default: addressOfString(""),
			},
			"issue-lock-reason": {
				Default: addressOfString("resolved"),
			},
			"pr-exclude-created-before": {
				Default: addressOfString(""),
			},
			"pr-exclude-labels": {
				Default: addressOfString(""),
			},
			"pr-lock-comment": {
				Default: addressOfString(""),
			},
			"pr-lock-inactive-days": {
				Default: addressOfString("365"),
			},
			"pr-lock-labels": {
				Default: addressOfString(""),
			},
			"pr-lock-reason": {
				Default: addressOfString("resolved"),
			},
			"process-only": {
				Default: addressOfString(""),
			},
		},
		Outputs: map[string]struct{}{
			"issues": {},
			"prs":    {},
		},
	},
	"docker/build-push-action@v1": {
		Name: "Build and push Docker images",
		Inputs: map[string]*ActionInput{
			"add_git_labels": {
				Default: addressOfString("false"),
			},
			"always_pull": {
				Default: addressOfString("false"),
			},
			"build_args":  {},
			"cache_froms": {},
			"dockerfile":  {},
			"labels":      {},
			"password":    {},
			"path": {
				Default: addressOfString("."),
			},
			"push": {
				Default: addressOfString("true"),
			},
			"registry": {},
			"repository": {
				Required: true,
			},
			"tag_with_ref": {
				Default: addressOfString("false"),
			},
			"tag_with_sha": {
				Default: addressOfString("false"),
			},
			"tags":     {},
			"target":   {},
			"username": {},
		},
	},
	"docker/build-push-action@v2": {
		Name: "Build and push Docker images",
		Inputs: map[string]*ActionInput{
			"allow":      {},
			"build-args": {},
			"builder":    {},
			"cache-from": {},
			"cache-to":   {},
			"context":    {},
			"file":       {},
			"github-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"labels": {},
			"load": {
				Default: addressOfString("false"),
			},
			"network": {},
			"no-cache": {
				Default: addressOfString("false"),
			},
			"outputs":   {},
			"platforms": {},
			"pull": {
				Default: addressOfString("false"),
			},
			"push": {
				Default: addressOfString("false"),
			},
			"secret-files": {},
			"secrets":      {},
			"ssh":          {},
			"tags":         {},
			"target":       {},
		},
		Outputs: map[string]struct{}{
			"digest": {},
		},
	},
	"docker/login-action@v1": {
		Name: "Docker Login",
		Inputs: map[string]*ActionInput{
			"logout": {
				Default: addressOfString("true"),
			},
			"password": {},
			"registry": {},
			"username": {},
		},
	},
	"docker/metadata-action@v1": {
		Name: "Docker Meta",
		Inputs: map[string]*ActionInput{
			"github-token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"images": {
				Required: true,
			},
			"label-custom":    {},
			"sep-labels":      {},
			"sep-tags":        {},
			"tag-custom":      {},
			"tag-custom-only": {},
			"tag-edge": {
				Default: addressOfString("false"),
			},
			"tag-edge-branch": {},
			"tag-latest": {
				Default: addressOfString("true"),
			},
			"tag-match": {},
			"tag-match-group": {
				Default: addressOfString("0"),
			},
			"tag-match-latest": {
				Default: addressOfString("true"),
			},
			"tag-schedule": {
				Default: addressOfString("nightly"),
			},
			"tag-semver": {},
			"tag-sha": {
				Default: addressOfString("false"),
			},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/metadata-action@v2": {
		Name: "Docker Meta",
		Inputs: map[string]*ActionInput{
			"bake-target": {},
			"flavor":      {},
			"github-token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"images": {
				Required: true,
			},
			"labels":     {},
			"sep-labels": {},
			"sep-tags":   {},
			"tags":       {},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/metadata-action@v3": {
		Name: "Docker Metadata action",
		Inputs: map[string]*ActionInput{
			"bake-target": {},
			"flavor":      {},
			"github-token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"images": {
				Required: true,
			},
			"labels":     {},
			"sep-labels": {},
			"sep-tags":   {},
			"tags":       {},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/setup-buildx-action@v1": {
		Name: "Docker Setup Buildx",
		Inputs: map[string]*ActionInput{
			"buildkitd-flags": {
				Default: addressOfString("--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host"),
			},
			"config": {},
			"driver": {
				Default: addressOfString("docker-container"),
			},
			"driver-opts": {},
			"endpoint":    {},
			"install": {
				Default: addressOfString("false"),
			},
			"use": {
				Default: addressOfString("true"),
			},
			"version": {},
		},
		Outputs: map[string]struct{}{
			"driver":    {},
			"endpoint":  {},
			"flags":     {},
			"name":      {},
			"platforms": {},
			"status":    {},
		},
	},
	"docker/setup-qemu-action@v1": {
		Name: "Docker Setup QEMU",
		Inputs: map[string]*ActionInput{
			"image": {
				Default: addressOfString("tonistiigi/binfmt:latest"),
			},
			"platforms": {
				Default: addressOfString("all"),
			},
		},
		Outputs: map[string]struct{}{
			"platforms": {},
		},
	},
	"dorny/paths-filter@v1": {
		Name: "Pull request changed files filter",
		Inputs: map[string]*ActionInput{
			"filters": {
				Required: true,
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"dorny/paths-filter@v2": {
		Name: "Paths Changes Filter",
		Inputs: map[string]*ActionInput{
			"base": {},
			"filters": {
				Required: true,
			},
			"initial-fetch-depth": {
				Default: addressOfString("100"),
			},
			"list-files": {
				Required: true,
				Default:  addressOfString("none"),
			},
			"ref": {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"working-directory": {},
		},
		Outputs: map[string]struct{}{
			"changes": {},
		},
	},
	"enriikke/gatsby-gh-pages-action@v2": {
		Name: "Gatsby Publish",
		Inputs: map[string]*ActionInput{
			"access-token": {
				Required: true,
			},
			"commit-message": {
				Default: addressOfString(""),
			},
			"deploy-branch": {
				Default: addressOfString("master"),
			},
			"deploy-repo": {
				Default: addressOfString(""),
			},
			"gatsby-args": {
				Default: addressOfString(""),
			},
			"git-config-email": {
				Default: addressOfString(""),
			},
			"git-config-name": {
				Default: addressOfString(""),
			},
			"skip-publish": {
				Default: addressOfString("false"),
			},
			"working-dir": {
				Default: addressOfString("."),
			},
		},
	},
	"erlef/setup-beam@v1": {
		Name: "Setup Erlang/OTP with optional Elixir (and mix) and/or rebar3",
		Inputs: map[string]*ActionInput{
			"elixir-version": {},
			"install-hex": {
				Default: addressOfString("true"),
			},
			"install-rebar": {
				Default: addressOfString("true"),
			},
			"otp-version":    {},
			"rebar3-version": {},
			"version-type": {
				Default: addressOfString("loose"),
			},
		},
		Outputs: map[string]struct{}{
			"elixir-version": {},
			"otp-version":    {},
			"rebar3-version": {},
		},
	},
	"game-ci/unity-builder@v2": {
		Name: "Unity - Builder",
		Inputs: map[string]*ActionInput{
			"allowDirtyBuild": {
				Default: addressOfString(""),
			},
			"androidAppBundle": {
				Default: addressOfString("false"),
			},
			"androidKeyaliasName": {
				Default: addressOfString(""),
			},
			"androidKeyaliasPass": {
				Default: addressOfString(""),
			},
			"androidKeystoreBase64": {
				Default: addressOfString(""),
			},
			"androidKeystoreName": {
				Default: addressOfString(""),
			},
			"androidKeystorePass": {
				Default: addressOfString(""),
			},
			"androidVersionCode": {
				Default: addressOfString(""),
			},
			"awsStackName": {
				Default: addressOfString("game-ci"),
			},
			"buildMethod": {
				Default: addressOfString(""),
			},
			"buildName": {
				Default: addressOfString(""),
			},
			"buildsPath": {
				Default: addressOfString(""),
			},
			"chownFilesTo": {
				Default: addressOfString(""),
			},
			"customImage": {
				Default: addressOfString(""),
			},
			"customParameters": {
				Default: addressOfString(""),
			},
			"githubToken": {
				Default: addressOfString(""),
			},
			"kubeConfig": {
				Default: addressOfString(""),
			},
			"kubeVolume": {
				Default: addressOfString(""),
			},
			"kubeVolumeSize": {
				Default: addressOfString("5Gi"),
			},
			"projectPath": {
				Default: addressOfString(""),
			},
			"remoteBuildCluster": {
				Default: addressOfString("local"),
			},
			"remoteBuildCpu": {
				Default: addressOfString("0.25"),
			},
			"remoteBuildMemory": {
				Default: addressOfString("800M"),
			},
			"sshAgent": {
				Default: addressOfString(""),
			},
			"targetPlatform": {
				Default: addressOfString(""),
			},
			"unityVersion": {
				Default: addressOfString("auto"),
			},
			"version": {
				Default: addressOfString(""),
			},
			"versioning": {
				Default: addressOfString("Semantic"),
			},
		},
		Outputs: map[string]struct{}{
			"buildVersion": {},
			"volume":       {},
		},
	},
	"getsentry/paths-filter@v1": {
		Name: "Pull request changed files filter",
		Inputs: map[string]*ActionInput{
			"filters": {
				Required: true,
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"getsentry/paths-filter@v2": {
		Name: "Paths Changes Filter",
		Inputs: map[string]*ActionInput{
			"base": {},
			"filters": {
				Required: true,
			},
			"initial-fetch-depth": {
				Default: addressOfString("100"),
			},
			"list-files": {
				Required: true,
				Default:  addressOfString("none"),
			},
			"ref": {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"working-directory": {},
		},
		Outputs: map[string]struct{}{
			"changes": {},
		},
	},
	"github/codeql-action/analyze@v1": {
		Name: "CodeQL: Finish",
		Inputs: map[string]*ActionInput{
			"add-snippets": {
				Default: addressOfString("false"),
			},
			"category":   {},
			"check_name": {},
			"checkout_path": {
				Default: addressOfString("${{ github.workspace }}"),
			},
			"cleanup-level": {
				Default: addressOfString("brutal"),
			},
			"matrix": {
				Default: addressOfString("${{ toJson(matrix) }}"),
			},
			"output": {
				Default: addressOfString("../results"),
			},
			"ram": {},
			"skip-queries": {
				Default: addressOfString("false"),
			},
			"threads": {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"upload": {
				Default: addressOfString("true"),
			},
			"upload-database": {
				Default: addressOfString("true"),
			},
		},
		Outputs: map[string]struct{}{
			"db-locations": {},
		},
	},
	"github/codeql-action/autobuild@v1": {
		Name: "CodeQL: Autobuild",
		Inputs: map[string]*ActionInput{
			"matrix": {
				Default: addressOfString("${{ toJson(matrix) }}"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
	},
	"github/codeql-action/init@v1": {
		Name: "CodeQL: Init",
		Inputs: map[string]*ActionInput{
			"config-file":               {},
			"db-location":               {},
			"external-repository-token": {},
			"languages":                 {},
			"matrix": {
				Default: addressOfString("${{ toJson(matrix) }}"),
			},
			"packs":   {},
			"queries": {},
			"setup-python-dependencies": {
				Required: true,
				Default:  addressOfString("true"),
			},
			"source-root": {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"tools": {},
		},
		Outputs: map[string]struct{}{
			"codeql-path": {},
		},
	},
	"github/super-linter@v3": {
		Name: "Super-Linter",
	},
	"github/super-linter@v4": {
		Name: "Super-Linter",
	},
	"githubocto/flat@v1": {
		Name: "Flat Data",
		Inputs: map[string]*ActionInput{
			"http_url": {},
			"outfile_basename": {
				Default: addressOfString("data"),
			},
			"postprocess":    {},
			"sql_connstring": {},
			"sql_format": {
				Default: addressOfString("json"),
			},
			"sql_queryfile": {
				Default: addressOfString(".github/workflows/query.sql"),
			},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"githubocto/flat@v2": {
		Name: "Flat Data",
		Inputs: map[string]*ActionInput{
			"downloaded_filename": {},
			"http_url":            {},
			"postprocess":         {},
			"sql_connstring":      {},
			"sql_queryfile": {
				Default: addressOfString(".github/workflows/query.sql"),
			},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"githubocto/flat@v3": {
		Name: "Flat Data",
		Inputs: map[string]*ActionInput{
			"authorization":       {},
			"axios_config":        {},
			"downloaded_filename": {},
			"http_url":            {},
			"mask":                {},
			"postprocess":         {},
			"sql_connstring":      {},
			"sql_queryfile": {
				Default: addressOfString(".github/workflows/query.sql"),
			},
			"typeorm_config": {},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"golangci/golangci-lint-action@v1": {
		Name: "Run golangci-lint",
		Inputs: map[string]*ActionInput{
			"args": {
				Default: addressOfString(""),
			},
			"github-token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"only-new-issues": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"version": {
				Required: true,
			},
			"working-directory": {},
		},
	},
	"golangci/golangci-lint-action@v2": {
		Name: "Run golangci-lint",
		Inputs: map[string]*ActionInput{
			"args": {
				Default: addressOfString(""),
			},
			"github-token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"only-new-issues": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"skip-build-cache": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"skip-go-installation": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"skip-pkg-cache": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"version":           {},
			"working-directory": {},
		},
	},
	"goreleaser/goreleaser-action@v1": {
		Name: "GoReleaser Action",
		Inputs: map[string]*ActionInput{
			"args": {},
			"key":  {},
			"version": {
				Default: addressOfString("latest"),
			},
			"workdir": {
				Default: addressOfString("."),
			},
		},
	},
	"goreleaser/goreleaser-action@v2": {
		Name: "GoReleaser Action",
		Inputs: map[string]*ActionInput{
			"args": {},
			"distribution": {
				Default: addressOfString("goreleaser"),
			},
			"install-only": {
				Default: addressOfString("false"),
			},
			"version": {
				Default: addressOfString("latest"),
			},
			"workdir": {
				Default: addressOfString("."),
			},
		},
	},
	"gradle/wrapper-validation-action@v1": {
		Name: "Gradle Wrapper Validation",
		Inputs: map[string]*ActionInput{
			"allow-checksums": {
				Default: addressOfString(""),
			},
			"allow-snapshots": {
				Default: addressOfString("false"),
			},
			"min-wrapper-count": {
				Default: addressOfString("1"),
			},
		},
	},
	"haskell/actions/setup@v1": {
		Name: "Setup Haskell",
		Inputs: map[string]*ActionInput{
			"cabal-version": {
				Default: addressOfString("latest"),
			},
			"disable-matcher": {},
			"enable-stack":    {},
			"ghc-version": {
				Default: addressOfString("latest"),
			},
			"stack-no-global": {},
			"stack-setup-ghc": {},
			"stack-version": {
				Default: addressOfString("latest"),
			},
		},
		Outputs: map[string]struct{}{
			"cabal-exe":   {},
			"cabal-path":  {},
			"cabal-store": {},
			"ghc-exe":     {},
			"ghc-path":    {},
			"stack-exe":   {},
			"stack-path":  {},
			"stack-root":  {},
		},
	},
	"marvinpinto/action-automatic-releases@latest": {
		Name: "Automatic Releases",
		Inputs: map[string]*ActionInput{
			"automatic_release_tag": {},
			"draft": {
				Default: addressOfString("false"),
			},
			"files": {},
			"prerelease": {
				Default: addressOfString("true"),
			},
			"repo_token": {
				Required: true,
			},
			"title": {},
		},
		Outputs: map[string]struct{}{
			"automatic_releases_tag": {},
			"upload_url":             {},
		},
	},
	"microsoft/playwright-github-action@v1": {
		Name: "Run Playwright tests",
	},
	"mikepenz/release-changelog-builder-action@v1": {
		Name: "Release Changelog Builder",
		Inputs: map[string]*ActionInput{
			"commitMode": {
				Default: addressOfString("false"),
			},
			"configuration": {},
			"failOnError": {
				Default: addressOfString("false"),
			},
			"fromTag": {},
			"ignorePreReleases": {
				Default: addressOfString("false"),
			},
			"outputFile": {},
			"owner":      {},
			"path":       {},
			"repo":       {},
			"toTag":      {},
			"token":      {},
		},
		Outputs: map[string]struct{}{
			"changelog": {},
			"failed":    {},
			"fromTag":   {},
			"owner":     {},
			"repo":      {},
			"toTag":     {},
		},
	},
	"mikepenz/release-changelog-builder-action@v2": {
		Name: "Release Changelog Builder",
		Inputs: map[string]*ActionInput{
			"commitMode": {
				Default: addressOfString("false"),
			},
			"configuration": {},
			"failOnError": {
				Default: addressOfString("false"),
			},
			"fromTag": {},
			"ignorePreReleases": {
				Default: addressOfString("false"),
			},
			"outputFile": {},
			"owner":      {},
			"path":       {},
			"repo":       {},
			"toTag":      {},
			"token":      {},
		},
		Outputs: map[string]struct{}{
			"changelog": {},
			"failed":    {},
			"fromTag":   {},
			"owner":     {},
			"repo":      {},
			"toTag":     {},
		},
	},
	"msys2/setup-msys2@v1": {
		Name: "Setup MSYS2 environment",
		Inputs: map[string]*ActionInput{
			"cache": {
				Default: addressOfString("false"),
			},
			"install": {
				Default: addressOfString("false"),
			},
			"msystem": {
				Default: addressOfString("MINGW64"),
			},
			"path-type": {
				Default: addressOfString("strict"),
			},
			"release": {
				Default: addressOfString("true"),
			},
			"update": {
				Default: addressOfString("false"),
			},
		},
	},
	"msys2/setup-msys2@v2": {
		Name: "Setup MSYS2",
		Inputs: map[string]*ActionInput{
			"install": {
				Default: addressOfString("false"),
			},
			"msystem": {
				Default: addressOfString("MINGW64"),
			},
			"path-type": {
				Default: addressOfString("minimal"),
			},
			"release": {
				Default: addressOfString("true"),
			},
			"update": {
				Default: addressOfString("false"),
			},
		},
	},
	"ncipollo/release-action@v1": {
		Name: "Create Release",
		Inputs: map[string]*ActionInput{
			"allowUpdates": {
				Default: addressOfString(""),
			},
			"artifact": {
				Default: addressOfString(""),
			},
			"artifactContentType": {
				Default: addressOfString(""),
			},
			"artifactErrorsFailBuild": {
				Default: addressOfString(""),
			},
			"artifacts": {
				Default: addressOfString(""),
			},
			"body": {
				Default: addressOfString(""),
			},
			"bodyFile": {
				Default: addressOfString(""),
			},
			"commit": {
				Default: addressOfString(""),
			},
			"discussionCategory": {
				Default: addressOfString(""),
			},
			"draft": {
				Default: addressOfString(""),
			},
			"name": {
				Default: addressOfString(""),
			},
			"omitBody": {
				Default: addressOfString("false"),
			},
			"omitBodyDuringUpdate": {
				Default: addressOfString("false"),
			},
			"omitName": {
				Default: addressOfString("false"),
			},
			"omitNameDuringUpdate": {
				Default: addressOfString("false"),
			},
			"owner": {
				Default: addressOfString(""),
			},
			"prerelease": {
				Default: addressOfString(""),
			},
			"replacesArtifacts": {
				Default: addressOfString("true"),
			},
			"repo": {
				Default: addressOfString(""),
			},
			"tag": {
				Default: addressOfString(""),
			},
			"token": {
				Required: true,
				Default:  addressOfString(""),
			},
		},
		Outputs: map[string]struct{}{
			"html_url":   {},
			"id":         {},
			"upload_url": {},
		},
	},
	"nwtgck/actions-netlify@v1": {
		Name: "Netlify Actions",
		Inputs: map[string]*ActionInput{
			"alias":                           {},
			"deploy-message":                  {},
			"enable-commit-comment":           {},
			"enable-commit-status":            {},
			"enable-pull-request-comment":     {},
			"fails-without-credentials":       {},
			"functions-dir":                   {},
			"github-deployment-description":   {},
			"github-deployment-environment":   {},
			"github-token":                    {},
			"netlify-config-path":             {},
			"overwrites-pull-request-comment": {},
			"production-branch":               {},
			"production-deploy":               {},
			"publish-dir": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"deploy-url": {},
		},
	},
	"octokit/request-action@v1.x": {
		Name: "GitHub API Request",
		Inputs: map[string]*ActionInput{
			"route": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"data":    {},
			"headers": {},
			"status":  {},
		},
	},
	"octokit/request-action@v2.x": {
		Name: "GitHub API Request",
		Inputs: map[string]*ActionInput{
			"mediaType": {
				Default: addressOfString("{}"),
			},
			"route": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"data":    {},
			"headers": {},
			"status":  {},
		},
	},
	"peaceiris/actions-gh-pages@v2": {
		Name: "GitHub Pages action",
		Inputs: map[string]*ActionInput{
			"commitMessage": {},
			"emptyCommits": {
				Default: addressOfString("true"),
			},
			"forceOrphan": {
				Default: addressOfString("false"),
			},
			"keepFiles": {
				Default: addressOfString("false"),
			},
			"tagMessage": {},
			"tagName":    {},
			"tagOverwrite": {
				Default: addressOfString("false"),
			},
			"useremail": {},
			"username":  {},
		},
	},
	"peaceiris/actions-gh-pages@v3": {
		Name: "GitHub Pages action",
		Inputs: map[string]*ActionInput{
			"allow_empty_commit": {
				Default: addressOfString("false"),
			},
			"cname":          {},
			"commit_message": {},
			"deploy_key":     {},
			"destination_dir": {
				Default: addressOfString(""),
			},
			"disable_nojekyll": {
				Default: addressOfString("false"),
			},
			"enable_jekyll": {
				Default: addressOfString("false"),
			},
			"exclude_assets": {
				Default: addressOfString(".github"),
			},
			"external_repository": {},
			"force_orphan": {
				Default: addressOfString("false"),
			},
			"full_commit_message": {},
			"github_token":        {},
			"keep_files": {
				Default: addressOfString("false"),
			},
			"personal_token": {},
			"publish_branch": {
				Default: addressOfString("gh-pages"),
			},
			"publish_dir": {
				Default: addressOfString("public"),
			},
			"tag_message": {},
			"tag_name":    {},
			"user_email":  {},
			"user_name":   {},
		},
	},
	"peter-evans/create-pull-request@v1": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionInput{
			"assignees":       {},
			"author-email":    {},
			"author-name":     {},
			"base":            {},
			"body":            {},
			"branch":          {},
			"branch-suffix":   {},
			"commit-message":  {},
			"committer-email": {},
			"committer-name":  {},
			"labels":          {},
			"milestone":       {},
			"project":         {},
			"project-column":  {},
			"reviewers":       {},
			"team-reviewers":  {},
			"title":           {},
			"token": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"pr_number": {},
		},
	},
	"peter-evans/create-pull-request@v2": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionInput{
			"assignees":      {},
			"author":         {},
			"base":           {},
			"body":           {},
			"branch":         {},
			"branch-suffix":  {},
			"commit-message": {},
			"committer":      {},
			"draft":          {},
			"labels":         {},
			"milestone":      {},
			"path":           {},
			"project":        {},
			"project-column": {},
			"request-to-parent": {
				Default: addressOfString("false"),
			},
			"reviewers":      {},
			"team-reviewers": {},
			"title":          {},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
		Outputs: map[string]struct{}{
			"pull-request-number": {},
		},
	},
	"peter-evans/create-pull-request@v3": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionInput{
			"assignees": {},
			"author": {
				Default: addressOfString("${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"),
			},
			"base": {},
			"body": {
				Default: addressOfString("Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action"),
			},
			"branch": {
				Default: addressOfString("create-pull-request/patch"),
			},
			"branch-suffix": {},
			"commit-message": {
				Default: addressOfString("[create-pull-request] automated change"),
			},
			"committer": {
				Default: addressOfString("GitHub <noreply@github.com>"),
			},
			"delete-branch": {
				Default: addressOfString("false"),
			},
			"draft": {
				Default: addressOfString("false"),
			},
			"labels":       {},
			"milestone":    {},
			"path":         {},
			"push-to-fork": {},
			"reviewers":    {},
			"signoff": {
				Default: addressOfString("false"),
			},
			"team-reviewers": {},
			"title": {
				Default: addressOfString("Changes by create-pull-request action"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
		},
		Outputs: map[string]struct{}{
			"pull-request-number": {},
		},
	},
	"preactjs/compressed-size-action@v1": {
		Name: "compressed-size-action",
		Inputs: map[string]*ActionInput{
			"build-script": {
				Default: addressOfString("build"),
			},
			"collapse-unchanged": {
				Default: addressOfString("true"),
			},
			"compression":    {},
			"omit-unchanged": {},
			"repo-token": {
				Required: true,
			},
			"show-total": {
				Default: addressOfString("true"),
			},
		},
	},
	"preactjs/compressed-size-action@v2": {
		Name: "compressed-size-action",
		Inputs: map[string]*ActionInput{
			"build-script": {
				Default: addressOfString("build"),
			},
			"clean-script": {},
			"collapse-unchanged": {
				Default: addressOfString("true"),
			},
			"compression": {},
			"cwd":         {},
			"exclude": {
				Default: addressOfString("{**/*.map,**/node_modules/**}"),
			},
			"minimum-change-threshold": {
				Default: addressOfString("1"),
			},
			"omit-unchanged": {},
			"pattern": {
				Default: addressOfString("**/dist/**/*.js"),
			},
			"repo-token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"show-total": {
				Default: addressOfString("true"),
			},
			"strip-hash": {},
			"use-check":  {},
		},
	},
	"reviewdog/action-actionlint@v1": {
		Name: "actionlint with reviewdog",
		Inputs: map[string]*ActionInput{
			"actionlint_flags": {
				Default: addressOfString(""),
			},
			"fail_on_error": {
				Required: true,
				Default:  addressOfString("false"),
			},
			"filter_mode": {
				Required: true,
				Default:  addressOfString("added"),
			},
			"github_token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"level": {
				Required: true,
				Default:  addressOfString("error"),
			},
			"reporter": {
				Required: true,
				Default:  addressOfString("github-pr-check"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"tool_name": {
				Required: true,
				Default:  addressOfString("golangci"),
			},
		},
	},
	"reviewdog/action-eslint@v1": {
		Name: "Run eslint with reviewdog",
		Inputs: map[string]*ActionInput{
			"eslint_flags": {
				Default: addressOfString("."),
			},
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"level": {
				Default: addressOfString("error"),
			},
			"reporter": {
				Default: addressOfString("github-pr-review"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"tool_name": {
				Default: addressOfString("eslint"),
			},
			"workdir": {
				Default: addressOfString("."),
			},
		},
	},
	"reviewdog/action-golangci-lint@v1": {
		Name: "Run golangci-lint with reviewdog",
		Inputs: map[string]*ActionInput{
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Required: true,
				Default:  addressOfString("${{ github.token }}"),
			},
			"golangci_lint_flags": {
				Default: addressOfString(""),
			},
			"level": {
				Default: addressOfString("error"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"tool_name": {
				Default: addressOfString("golangci"),
			},
			"workdir": {
				Default: addressOfString("."),
			},
		},
	},
	"reviewdog/action-hadolint@v1": {
		Name: "Run hadolint with reviewdog",
		Inputs: map[string]*ActionInput{
			"exclude": {
				Default: addressOfString(""),
			},
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"hadolint_flags": {
				Default: addressOfString(""),
			},
			"hadolint_ignore": {
				Default: addressOfString(""),
			},
			"level": {
				Default: addressOfString("error"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"tool_name": {
				Default: addressOfString("hadolint"),
			},
		},
	},
	"reviewdog/action-misspell@v1": {
		Name: "Run misspell with reviewdog",
		Inputs: map[string]*ActionInput{
			"exclude": {
				Default: addressOfString(""),
			},
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"ignore": {
				Default: addressOfString(""),
			},
			"level": {
				Default: addressOfString("error"),
			},
			"locale": {
				Default: addressOfString(""),
			},
			"path": {
				Default: addressOfString("."),
			},
			"pattern": {
				Default: addressOfString("*"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
		},
	},
	"reviewdog/action-rubocop@v1": {
		Name: "Run rubocop with reviewdog",
		Inputs: map[string]*ActionInput{
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Required: true,
			},
			"level": {
				Default: addressOfString("error"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"rubocop_extensions": {
				Default: addressOfString("rubocop-rails rubocop-performance rubocop-rspec rubocop-i18n rubocop-rake"),
			},
			"rubocop_flags": {
				Default: addressOfString(""),
			},
			"rubocop_version": {},
			"tool_name": {
				Default: addressOfString("rubocop"),
			},
			"workdir": {
				Default: addressOfString("."),
			},
		},
	},
	"reviewdog/action-shellcheck@v1": {
		Name: "Run shellcheck with reviewdog",
		Inputs: map[string]*ActionInput{
			"exclude": {},
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"github_token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"level": {
				Default: addressOfString("error"),
			},
			"path": {
				Default: addressOfString("."),
			},
			"pattern": {
				Default: addressOfString("*.sh"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
			"reviewdog_flags": {
				Default: addressOfString(""),
			},
			"shellcheck_flags": {
				Default: addressOfString("--external-sources"),
			},
		},
	},
	"reviewdog/action-tflint@v1": {
		Name: "Run tflint with reviewdog",
		Inputs: map[string]*ActionInput{
			"fail_on_error": {
				Default: addressOfString("false"),
			},
			"filter_mode": {
				Default: addressOfString("added"),
			},
			"flags": {
				Default: addressOfString("--module"),
			},
			"github_token": {
				Required: true,
			},
			"level": {
				Default: addressOfString("error"),
			},
			"reporter": {
				Default: addressOfString("github-pr-check"),
			},
			"tflint_rulesets": {
				Default: addressOfString(""),
			},
			"tflint_version": {
				Default: addressOfString("latest"),
			},
			"working_directory": {
				Default: addressOfString("."),
			},
		},
		Outputs: map[string]struct{}{
			"reviewdog-return-code": {},
			"tflint-return-code":    {},
		},
	},
	"rhysd/action-setup-vim@v1": {
		Name: "Setup Vim",
		Inputs: map[string]*ActionInput{
			"neovim": {
				Default: addressOfString("false"),
			},
			"token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"version": {
				Default: addressOfString("stable"),
			},
		},
		Outputs: map[string]struct{}{
			"executable": {},
		},
	},
	"ridedott/merge-me-action@v1": {
		Name: "Merge me!",
		Inputs: map[string]*ActionInput{
			"GITHUB_LOGIN": {
				Default: addressOfString("dependabot-preview[bot]"),
			},
			"GITHUB_TOKEN": {
				Required: true,
			},
			"MERGE_METHOD": {
				Default: addressOfString("SQUASH"),
			},
			"PRESET": {},
		},
	},
	"ridedott/merge-me-action@v2": {
		Name: "Merge me!",
		Inputs: map[string]*ActionInput{
			"ENABLED_FOR_MANUAL_CHANGES": {
				Default: addressOfString("false"),
			},
			"ENABLE_GITHUB_API_PREVIEW": {
				Default: addressOfString("false"),
			},
			"GITHUB_LOGIN": {
				Default: addressOfString("dependabot"),
			},
			"GITHUB_TOKEN": {
				Required: true,
			},
			"MAXIMUM_RETRIES": {
				Default: addressOfString("3"),
			},
			"MERGE_METHOD": {
				Default: addressOfString("SQUASH"),
			},
			"PRESET": {},
		},
	},
	"rtCamp/action-slack-notify@v2": {
		Name: "Slack Notify",
	},
	"ruby/setup-ruby@v1": {
		Name: "Setup Ruby, JRuby and TruffleRuby",
		Inputs: map[string]*ActionInput{
			"bundler": {
				Default: addressOfString("default"),
			},
			"bundler-cache": {
				Default: addressOfString("false"),
			},
			"cache-version": {
				Default: addressOfString("0"),
			},
			"ruby-version": {
				Default: addressOfString("default"),
			},
			"working-directory": {
				Default: addressOfString("."),
			},
		},
		Outputs: map[string]struct{}{
			"ruby-prefix": {},
		},
	},
	"shivammathur/setup-php@v1": {
		Name: "Setup PHP Action",
		Inputs: map[string]*ActionInput{
			"coverage":       {},
			"extension-csv":  {},
			"extensions":     {},
			"ini-values":     {},
			"ini-values-csv": {},
			"pecl":           {},
			"php-version": {
				Required: true,
				Default:  addressOfString("7.4"),
			},
			"tools": {},
		},
	},
	"shivammathur/setup-php@v2": {
		Name: "Setup PHP Action",
		Inputs: map[string]*ActionInput{
			"coverage":   {},
			"extensions": {},
			"ini-values": {},
			"php-version": {
				Required: true,
				Default:  addressOfString("8.0"),
			},
			"tools": {},
		},
		Outputs: map[string]struct{}{
			"php-version": {},
		},
	},
	"softprops/action-gh-release@v1": {
		Name: "GH Release",
		Inputs: map[string]*ActionInput{
			"body":       {},
			"body_path":  {},
			"draft":      {},
			"files":      {},
			"name":       {},
			"prerelease": {},
			"tag_name":   {},
		},
		Outputs: map[string]struct{}{
			"url": {},
		},
	},
	"subosito/flutter-action@v1": {
		Name: "Flutter action",
		Inputs: map[string]*ActionInput{
			"channel": {
				Default: addressOfString("stable"),
			},
			"flutter-version": {},
		},
	},
	"treosh/lighthouse-ci-action@v1": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionInput{
			"url":  {},
			"urls": {},
		},
		Outputs: map[string]struct{}{
			"resultsPath": {},
		},
	},
	"treosh/lighthouse-ci-action@v2": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionInput{
			"budgetPath": {},
			"configPath": {},
			"runs": {
				Default: addressOfString("1"),
			},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"resultsPath": {},
		},
	},
	"treosh/lighthouse-ci-action@v3": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionInput{
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"treosh/lighthouse-ci-action@v7": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionInput{
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"treosh/lighthouse-ci-action@v8": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionInput{
			"artifactName": {
				Default: addressOfString("lighthouse-results"),
			},
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"wearerequired/lint-action@v1": {
		Name: "Lint Action",
		Inputs: map[string]*ActionInput{
			"auto_fix": {
				Default: addressOfString("false"),
			},
			"black": {
				Default: addressOfString("false"),
			},
			"black_args": {
				Default: addressOfString(""),
			},
			"black_command_prefix": {
				Default: addressOfString(""),
			},
			"black_dir": {},
			"black_extensions": {
				Default: addressOfString("py"),
			},
			"check_name": {
				Default: addressOfString("${linter}"),
			},
			"commit_message": {
				Default: addressOfString("Fix code style issues with ${linter}"),
			},
			"continue_on_error": {
				Default: addressOfString("true"),
			},
			"eslint": {
				Default: addressOfString("false"),
			},
			"eslint_args": {
				Default: addressOfString(""),
			},
			"eslint_command_prefix": {
				Default: addressOfString(""),
			},
			"eslint_dir": {},
			"eslint_extensions": {
				Default: addressOfString("js"),
			},
			"flake8": {
				Default: addressOfString("false"),
			},
			"flake8_args": {
				Default: addressOfString(""),
			},
			"flake8_command_prefix": {
				Default: addressOfString(""),
			},
			"flake8_dir": {},
			"flake8_extensions": {
				Default: addressOfString("py"),
			},
			"git_email": {
				Default: addressOfString("lint-action@samuelmeuli.com"),
			},
			"git_name": {
				Default: addressOfString("Lint Action"),
			},
			"github_token": {
				Default: addressOfString("${{ github.token }}"),
			},
			"gofmt": {
				Default: addressOfString("false"),
			},
			"gofmt_args": {
				Default: addressOfString(""),
			},
			"gofmt_command_prefix": {
				Default: addressOfString(""),
			},
			"gofmt_dir": {},
			"gofmt_extensions": {
				Default: addressOfString("go"),
			},
			"golint": {
				Default: addressOfString("false"),
			},
			"golint_args": {
				Default: addressOfString(""),
			},
			"golint_command_prefix": {
				Default: addressOfString(""),
			},
			"golint_dir": {},
			"golint_extensions": {
				Default: addressOfString("go"),
			},
			"mypy": {
				Default: addressOfString("false"),
			},
			"mypy_args": {
				Default: addressOfString(""),
			},
			"mypy_command_prefix": {
				Default: addressOfString(""),
			},
			"mypy_dir": {},
			"mypy_extensions": {
				Default: addressOfString("py"),
			},
			"neutral_check_on_warning": {
				Default: addressOfString("false"),
			},
			"oitnb": {
				Default: addressOfString("false"),
			},
			"oitnb_args": {
				Default: addressOfString(""),
			},
			"oitnb_command_prefix": {
				Default: addressOfString(""),
			},
			"oitnb_dir": {},
			"oitnb_extensions": {
				Default: addressOfString("py"),
			},
			"php_codesniffer": {
				Default: addressOfString("false"),
			},
			"php_codesniffer_args": {
				Default: addressOfString(""),
			},
			"php_codesniffer_command_prefix": {
				Default: addressOfString(""),
			},
			"php_codesniffer_dir": {},
			"php_codesniffer_extensions": {
				Default: addressOfString("php"),
			},
			"prettier": {
				Default: addressOfString("false"),
			},
			"prettier_args": {
				Default: addressOfString(""),
			},
			"prettier_command_prefix": {
				Default: addressOfString(""),
			},
			"prettier_dir": {},
			"prettier_extensions": {
				Default: addressOfString("css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml"),
			},
			"rubocop": {
				Default: addressOfString("false"),
			},
			"rubocop_args": {
				Default: addressOfString(""),
			},
			"rubocop_command_prefix": {
				Default: addressOfString(""),
			},
			"rubocop_dir": {},
			"rubocop_extensions": {
				Default: addressOfString("rb"),
			},
			"stylelint": {
				Default: addressOfString("false"),
			},
			"stylelint_args": {
				Default: addressOfString(""),
			},
			"stylelint_command_prefix": {
				Default: addressOfString(""),
			},
			"stylelint_dir": {},
			"stylelint_extensions": {
				Default: addressOfString("css,sass,scss"),
			},
			"swift_format_lockwood": {
				Default: addressOfString("false"),
			},
			"swift_format_lockwood_args": {
				Default: addressOfString(""),
			},
			"swift_format_lockwood_command_prefix": {
				Default: addressOfString(""),
			},
			"swift_format_lockwood_dir": {},
			"swift_format_lockwood_extensions": {
				Default: addressOfString("swift"),
			},
			"swift_format_official": {
				Default: addressOfString("false"),
			},
			"swift_format_official_args": {
				Default: addressOfString(""),
			},
			"swift_format_official_command_prefix": {
				Default: addressOfString(""),
			},
			"swift_format_official_dir": {},
			"swift_format_official_extensions": {
				Default: addressOfString("swift"),
			},
			"swiftformat": {
				Default: addressOfString("false"),
			},
			"swiftformat_args": {
				Default: addressOfString(""),
			},
			"swiftformat_command_prefix": {
				Default: addressOfString(""),
			},
			"swiftformat_dir": {},
			"swiftformat_extensions": {
				Default: addressOfString("swift"),
			},
			"swiftlint": {
				Default: addressOfString("false"),
			},
			"swiftlint_args": {
				Default: addressOfString(""),
			},
			"swiftlint_command_prefix": {
				Default: addressOfString(""),
			},
			"swiftlint_dir": {},
			"swiftlint_extensions": {
				Default: addressOfString("swift"),
			},
			"xo": {
				Default: addressOfString("false"),
			},
			"xo_args": {
				Default: addressOfString(""),
			},
			"xo_command_prefix": {
				Default: addressOfString(""),
			},
			"xo_dir": {},
			"xo_extensions": {
				Default: addressOfString("js"),
			},
		},
	},
}
