// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionMetadata{
	"8398a7/action-slack@v1": {
		Name: "action-slack",
		Inputs: map[string]*ActionMetadataInput{
			"failedMention": {
				Default: &popularActionDefaultValue0,
			},
			"payload": {},
			"text":    {},
			"type":    {},
		},
	},
	"8398a7/action-slack@v2": {
		Name: "action-slack",
		Inputs: map[string]*ActionMetadataInput{
			"author_name": {
				Default: &popularActionDefaultValue1,
			},
			"channel": {
				Default: &popularActionDefaultValue2,
			},
			"icon_emoji": {
				Default: &popularActionDefaultValue2,
			},
			"icon_url": {
				Default: &popularActionDefaultValue2,
			},
			"mention": {
				Default: &popularActionDefaultValue2,
			},
			"only_mention_fail": {
				Default: &popularActionDefaultValue2,
			},
			"payload": {},
			"status":  {},
			"text": {
				Default: &popularActionDefaultValue2,
			},
			"username": {
				Default: &popularActionDefaultValue2,
			},
		},
	},
	"8398a7/action-slack@v3": {
		Name: "action-slack",
		Inputs: map[string]*ActionMetadataInput{
			"author_name": {
				Default: &popularActionDefaultValue1,
			},
			"channel": {
				Default: &popularActionDefaultValue2,
			},
			"custom_payload": {},
			"fields": {
				Default: &popularActionDefaultValue2,
			},
			"github_base_url": {
				Default: &popularActionDefaultValue2,
			},
			"github_token": {
				Default: &popularActionDefaultValue3,
			},
			"icon_emoji": {
				Default: &popularActionDefaultValue2,
			},
			"icon_url": {
				Default: &popularActionDefaultValue2,
			},
			"if_mention": {
				Default: &popularActionDefaultValue2,
			},
			"job_name": {
				Default: &popularActionDefaultValue2,
			},
			"mention": {
				Default: &popularActionDefaultValue2,
			},
			"status": {
				Required: true,
			},
			"text": {
				Default: &popularActionDefaultValue2,
			},
			"username": {
				Default: &popularActionDefaultValue2,
			},
		},
	},
	"Azure/container-scan@v0": {
		Name: "Container image scan",
		Inputs: map[string]*ActionMetadataInput{
			"image-name": {
				Required: true,
			},
			"password": {},
			"run-quality-checks": {
				Default: &popularActionDefaultValue4,
			},
			"severity-threshold": {
				Default: &popularActionDefaultValue5,
			},
			"token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"username": {},
		},
		Outputs: map[string]struct{}{
			"check-run-url":    {},
			"scan-report-path": {},
		},
	},
	"Azure/functions-action@v1": {
		Name: "Azure Functions Action",
		Inputs: map[string]*ActionMetadataInput{
			"app-name": {
				Required: true,
			},
			"enable-oryx-build": {
				Default: &popularActionDefaultValue6,
			},
			"package": {
				Default: &popularActionDefaultValue7,
			},
			"publish-profile": {},
			"respect-funcignore": {
				Default: &popularActionDefaultValue6,
			},
			"respect-pom-xml": {
				Default: &popularActionDefaultValue6,
			},
			"scm-do-build-during-deployment": {
				Default: &popularActionDefaultValue6,
			},
			"slot-name": {},
		},
		Outputs: map[string]struct{}{
			"app-url": {},
		},
	},
	"EnricoMi/publish-unit-test-result-action@v1": {
		Name: "Publish Unit Test Results",
		Inputs: map[string]*ActionMetadataInput{
			"check_name": {
				Default: &popularActionDefaultValue8,
			},
			"check_run_annotations": {
				Default: &popularActionDefaultValue9,
			},
			"check_run_annotations_branch": {},
			"comment_mode": {
				Default: &popularActionDefaultValue10,
			},
			"comment_on_pr": {},
			"comment_title": {},
			"commit":        {},
			"compare_to_earlier_commit": {
				Default: &popularActionDefaultValue4,
			},
			"deduplicate_classes_by_file_name": {},
			"fail_on": {
				Default: &popularActionDefaultValue11,
			},
			"files": {
				Required: true,
			},
			"github_retries": {
				Default: &popularActionDefaultValue12,
			},
			"github_token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"hide_comments": {
				Default: &popularActionDefaultValue13,
			},
			"pull_request_build": {
				Default: &popularActionDefaultValue14,
			},
			"report_individual_runs": {},
			"seconds_between_github_reads": {
				Default: &popularActionDefaultValue15,
			},
			"seconds_between_github_writes": {
				Default: &popularActionDefaultValue16,
			},
			"test_changes_limit": {},
		},
	},
	"JamesIves/github-pages-deploy-action@releases/v3": {
		Name: "Deploy to GitHub Pages",
		Inputs: map[string]*ActionMetadataInput{
			"ACCESS_TOKEN": {},
			"BASE_BRANCH":  {},
			"BRANCH": {
				Required: true,
			},
			"CLEAN": {
				Default: &popularActionDefaultValue4,
			},
			"CLEAN_EXCLUDE":  {},
			"COMMIT_MESSAGE": {},
			"FOLDER": {
				Required: true,
			},
			"GITHUB_TOKEN":     {},
			"GIT_CONFIG_EMAIL": {},
			"GIT_CONFIG_NAME":  {},
			"LFS":              {},
			"PRESERVE":         {},
			"REPOSITORY_NAME":  {},
			"SILENT":           {},
			"SINGLE_COMMIT":    {},
			"SSH":              {},
			"TARGET_FOLDER":    {},
			"WORKSPACE":        {},
		},
		Outputs: map[string]struct{}{
			"DEPLOYMENT_STATUS": {},
		},
	},
	"JamesIves/github-pages-deploy-action@releases/v4": {
		Name: "Deploy to GitHub Pages",
		Inputs: map[string]*ActionMetadataInput{
			"branch": {
				Required: true,
			},
			"clean": {
				Default: &popularActionDefaultValue4,
			},
			"clean-exclude":  {},
			"commit-message": {},
			"dry-run":        {},
			"folder": {
				Required: true,
			},
			"git-config-email": {},
			"git-config-name":  {},
			"repository-name":  {},
			"silent":           {},
			"single-commit":    {},
			"ssh-key":          {},
			"target-folder":    {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"workspace": {},
		},
		Outputs: map[string]struct{}{
			"deployment-status": {},
		},
	},
	"ReactiveCircus/android-emulator-runner@v1": {
		Name: "Android Emulator Runner",
		Inputs: map[string]*ActionMetadataInput{
			"api-level": {
				Required: true,
			},
			"arch": {
				Default: &popularActionDefaultValue17,
			},
			"disable-animations": {
				Default: &popularActionDefaultValue4,
			},
			"headless": {
				Default: &popularActionDefaultValue4,
			},
			"profile": {},
			"script": {
				Required: true,
			},
			"target": {
				Default: &popularActionDefaultValue18,
			},
		},
	},
	"ReactiveCircus/android-emulator-runner@v2": {
		Name: "Android Emulator Runner",
		Inputs: map[string]*ActionMetadataInput{
			"api-level": {
				Required: true,
			},
			"arch": {
				Default: &popularActionDefaultValue17,
			},
			"avd-name": {
				Default: &popularActionDefaultValue19,
			},
			"cmake": {},
			"cores": {
				Default: &popularActionDefaultValue20,
			},
			"disable-animations": {
				Default: &popularActionDefaultValue4,
			},
			"disable-linux-hw-accel": {
				Default: &popularActionDefaultValue4,
			},
			"disable-spellchecker": {
				Default: &popularActionDefaultValue6,
			},
			"emulator-build": {},
			"emulator-options": {
				Default: &popularActionDefaultValue21,
			},
			"force-avd-creation": {
				Default: &popularActionDefaultValue4,
			},
			"ndk":      {},
			"profile":  {},
			"ram-size": {},
			"script": {
				Required: true,
			},
			"sdcard-path-or-size": {},
			"target": {
				Default: &popularActionDefaultValue18,
			},
			"working-directory": {},
		},
	},
	"actions-cool/issues-helper@v1": {
		Name: "Issues Helper",
		Inputs: map[string]*ActionMetadataInput{
			"actions":         {},
			"assignees":       {},
			"body":            {},
			"body-includes":   {},
			"comment-auth":    {},
			"comment-id":      {},
			"contents":        {},
			"direction":       {},
			"inactive-day":    {},
			"inactive-label":  {},
			"issue-assignee":  {},
			"issue-creator":   {},
			"issue-mentioned": {},
			"issue-number":    {},
			"issue-state":     {},
			"labels":          {},
			"state":           {},
			"title":           {},
			"title-includes":  {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"update-mode": {},
		},
		Outputs: map[string]struct{}{
			"comment-id":   {},
			"comments":     {},
			"issue-number": {},
		},
	},
	"actions-cool/issues-helper@v2": {
		Name: "Issues Helper",
		Inputs: map[string]*ActionMetadataInput{
			"actions":            {},
			"assignee-includes":  {},
			"assignees":          {},
			"body":               {},
			"body-includes":      {},
			"close-issue":        {},
			"comment-auth":       {},
			"comment-id":         {},
			"contents":           {},
			"count-comments":     {},
			"count-lables":       {},
			"direction":          {},
			"duplicate-command":  {},
			"duplicate-labels":   {},
			"inactive-day":       {},
			"inactive-label":     {},
			"issue-assignee":     {},
			"issue-contents":     {},
			"issue-creator":      {},
			"issue-mentioned":    {},
			"issue-number":       {},
			"issue-state":        {},
			"labels":             {},
			"lock-reason":        {},
			"random-to":          {},
			"remove-labels":      {},
			"require-permission": {},
			"state":              {},
			"title":              {},
			"title-includes":     {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"update-mode": {},
		},
		Outputs: map[string]struct{}{
			"check-result": {},
			"comment-id":   {},
			"comments":     {},
			"issue-number": {},
		},
	},
	"actions-rs/audit-check@v1": {
		Name: "rust-audit-check",
		Inputs: map[string]*ActionMetadataInput{
			"token": {
				Required: true,
			},
		},
	},
	"actions-rs/cargo@v1": {
		Name: "rust-cargo",
		Inputs: map[string]*ActionMetadataInput{
			"args": {},
			"command": {
				Required: true,
			},
			"toolchain": {},
			"use-cross": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"actions-rs/clippy-check@v1": {
		Name: "rust-clippy-check",
		Inputs: map[string]*ActionMetadataInput{
			"args": {},
			"name": {
				Default: &popularActionDefaultValue22,
			},
			"token": {
				Required: true,
			},
			"toolchain": {},
			"use-cross": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"actions-rs/toolchain@v1": {
		Name: "rust-toolchain",
		Inputs: map[string]*ActionMetadataInput{
			"components": {},
			"default": {
				Default: &popularActionDefaultValue6,
			},
			"override": {
				Default: &popularActionDefaultValue6,
			},
			"profile":   {},
			"target":    {},
			"toolchain": {},
		},
		Outputs: map[string]struct{}{
			"cargo":      {},
			"rustc":      {},
			"rustc_hash": {},
			"rustup":     {},
		},
	},
	"actions/cache@v1": {
		Name: "Cache",
		Inputs: map[string]*ActionMetadataInput{
			"key": {
				Required: true,
			},
			"path": {
				Required: true,
			},
			"restore-keys": {},
		},
		Outputs: map[string]struct{}{
			"cache-hit": {},
		},
	},
	"actions/cache@v2": {
		Name: "Cache",
		Inputs: map[string]*ActionMetadataInput{
			"key": {
				Required: true,
			},
			"path": {
				Required: true,
			},
			"restore-keys":      {},
			"upload-chunk-size": {},
		},
		Outputs: map[string]struct{}{
			"cache-hit": {},
		},
	},
	"actions/checkout@v1": {
		Name: "Checkout",
		Inputs: map[string]*ActionMetadataInput{
			"clean": {
				Default: &popularActionDefaultValue4,
			},
			"fetch-depth": {},
			"lfs":         {},
			"path":        {},
			"ref":         {},
			"repository":  {},
			"submodules":  {},
			"token":       {},
		},
	},
	"actions/checkout@v2": {
		Name: "Checkout",
		Inputs: map[string]*ActionMetadataInput{
			"clean": {
				Default: &popularActionDefaultValue4,
			},
			"fetch-depth": {
				Default: &popularActionDefaultValue23,
			},
			"lfs": {
				Default: &popularActionDefaultValue6,
			},
			"path": {},
			"persist-credentials": {
				Default: &popularActionDefaultValue4,
			},
			"ref": {},
			"repository": {
				Default: &popularActionDefaultValue24,
			},
			"ssh-key":         {},
			"ssh-known-hosts": {},
			"ssh-strict": {
				Default: &popularActionDefaultValue4,
			},
			"submodules": {
				Default: &popularActionDefaultValue6,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
	},
	"actions/delete-package-versions@v1": {
		Name: "Delete Package Versions",
		Inputs: map[string]*ActionMetadataInput{
			"num-old-versions-to-delete": {
				Default: &popularActionDefaultValue23,
			},
			"owner":               {},
			"package-name":        {},
			"package-version-ids": {},
			"repo":                {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
	},
	"actions/download-artifact@v1": {
		Name: "Download a Build Artifact",
		Inputs: map[string]*ActionMetadataInput{
			"name": {
				Required: true,
			},
			"path": {},
		},
	},
	"actions/download-artifact@v2": {
		Name: "Download a Build Artifact",
		Inputs: map[string]*ActionMetadataInput{
			"name": {},
			"path": {},
		},
	},
	"actions/first-interaction@v1": {
		Name: "First interaction",
		Inputs: map[string]*ActionMetadataInput{
			"issue-message": {},
			"pr-message":    {},
			"repo-token": {
				Required: true,
			},
		},
	},
	"actions/github-script@v1": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionMetadataInput{
			"debug": {
				Default: &popularActionDefaultValue6,
			},
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"previews": {},
			"result-encoding": {
				Default: &popularActionDefaultValue25,
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: &popularActionDefaultValue26,
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v2": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionMetadataInput{
			"debug": {
				Default: &popularActionDefaultValue6,
			},
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"previews": {},
			"result-encoding": {
				Default: &popularActionDefaultValue25,
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: &popularActionDefaultValue26,
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v3": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionMetadataInput{
			"debug": {
				Default: &popularActionDefaultValue6,
			},
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"previews": {},
			"result-encoding": {
				Default: &popularActionDefaultValue25,
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: &popularActionDefaultValue26,
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/github-script@v4": {
		Name: "GitHub Script",
		Inputs: map[string]*ActionMetadataInput{
			"debug": {
				Default: &popularActionDefaultValue6,
			},
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"previews": {},
			"result-encoding": {
				Default: &popularActionDefaultValue25,
			},
			"script": {
				Required: true,
			},
			"user-agent": {
				Default: &popularActionDefaultValue26,
			},
		},
		Outputs: map[string]struct{}{
			"result": {},
		},
	},
	"actions/labeler@v2": {
		Name: "Pull Request Labeler",
		Inputs: map[string]*ActionMetadataInput{
			"configuration-path": {
				Default: &popularActionDefaultValue27,
			},
			"repo-token": {},
			"sync-labels": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"actions/labeler@v3": {
		Name: "Labeler",
		Inputs: map[string]*ActionMetadataInput{
			"configuration-path": {
				Default: &popularActionDefaultValue27,
			},
			"repo-token": {},
			"sync-labels": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"actions/setup-dotnet@v1": {
		Name: "Setup .NET Core SDK",
		Inputs: map[string]*ActionMetadataInput{
			"config-file":        {},
			"dotnet-version":     {},
			"include-prerelease": {},
			"owner":              {},
			"source-url":         {},
		},
	},
	"actions/setup-go@v1": {
		Name: "Setup Go environment",
		Inputs: map[string]*ActionMetadataInput{
			"go-version": {
				Default: &popularActionDefaultValue28,
			},
			"version": {},
		},
	},
	"actions/setup-go@v2": {
		Name: "Setup Go environment",
		Inputs: map[string]*ActionMetadataInput{
			"go-version": {},
			"stable": {
				Default: &popularActionDefaultValue4,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
	},
	"actions/setup-java@v1": {
		Name: "Setup Java JDK",
		Inputs: map[string]*ActionMetadataInput{
			"architecture": {
				Default: &popularActionDefaultValue29,
			},
			"gpg-passphrase":  {},
			"gpg-private-key": {},
			"java-package": {
				Default: &popularActionDefaultValue30,
			},
			"java-version": {
				Required: true,
			},
			"jdkFile": {},
			"server-id": {
				Default: &popularActionDefaultValue31,
			},
			"server-password": {
				Default: &popularActionDefaultValue32,
			},
			"server-username": {
				Default: &popularActionDefaultValue33,
			},
			"settings-path": {},
		},
		Outputs: map[string]struct{}{
			"path":    {},
			"version": {},
		},
	},
	"actions/setup-java@v2": {
		Name: "Setup Java JDK",
		Inputs: map[string]*ActionMetadataInput{
			"architecture": {
				Default: &popularActionDefaultValue29,
			},
			"check-latest": {
				Default: &popularActionDefaultValue6,
			},
			"distribution": {
				Required: true,
			},
			"gpg-passphrase":  {},
			"gpg-private-key": {},
			"java-package": {
				Default: &popularActionDefaultValue30,
			},
			"java-version": {
				Required: true,
			},
			"jdkFile": {},
			"overwrite-settings": {
				Default: &popularActionDefaultValue4,
			},
			"server-id": {
				Default: &popularActionDefaultValue31,
			},
			"server-password": {
				Default: &popularActionDefaultValue32,
			},
			"server-username": {
				Default: &popularActionDefaultValue33,
			},
			"settings-path": {},
		},
		Outputs: map[string]struct{}{
			"distribution": {},
			"path":         {},
			"version":      {},
		},
	},
	"actions/setup-node@v1": {
		Name: "Setup Node.js environment",
		Inputs: map[string]*ActionMetadataInput{
			"always-auth": {
				Default: &popularActionDefaultValue6,
			},
			"node-version": {
				Default: &popularActionDefaultValue34,
			},
			"registry-url": {},
			"scope":        {},
			"version":      {},
		},
	},
	"actions/setup-node@v2": {
		Name: "Setup Node.js environment",
		Inputs: map[string]*ActionMetadataInput{
			"always-auth": {
				Default: &popularActionDefaultValue6,
			},
			"architecture":          {},
			"cache":                 {},
			"cache-dependency-path": {},
			"check-latest": {
				Default: &popularActionDefaultValue6,
			},
			"node-version": {},
			"registry-url": {},
			"scope":        {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"version": {},
		},
	},
	"actions/setup-python@v1": {
		Name: "Setup Python",
		Inputs: map[string]*ActionMetadataInput{
			"architecture": {
				Default: &popularActionDefaultValue29,
			},
			"python-version": {
				Default: &popularActionDefaultValue35,
			},
		},
		Outputs: map[string]struct{}{
			"python-version": {},
		},
	},
	"actions/setup-python@v2": {
		Name: "Setup Python",
		Inputs: map[string]*ActionMetadataInput{
			"architecture": {},
			"python-version": {
				Default: &popularActionDefaultValue35,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		Outputs: map[string]struct{}{
			"python-version": {},
		},
	},
	"actions/stale@v1": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionMetadataInput{
			"days-before-close": {
				Default: &popularActionDefaultValue36,
			},
			"days-before-stale": {
				Default: &popularActionDefaultValue37,
			},
			"exempt-issue-label": {},
			"exempt-pr-label":    {},
			"operations-per-run": {
				Default: &popularActionDefaultValue38,
			},
			"repo-token": {
				Required: true,
			},
			"stale-issue-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-pr-message": {},
		},
	},
	"actions/stale@v2": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionMetadataInput{
			"days-before-close": {
				Default: &popularActionDefaultValue36,
			},
			"days-before-stale": {
				Default: &popularActionDefaultValue37,
			},
			"debug-only": {
				Default: &popularActionDefaultValue6,
			},
			"exempt-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"only-labels": {
				Default: &popularActionDefaultValue2,
			},
			"operations-per-run": {
				Default: &popularActionDefaultValue38,
			},
			"repo-token": {
				Required: true,
			},
			"stale-issue-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-pr-message": {},
		},
	},
	"actions/stale@v3": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionMetadataInput{
			"any-of-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"any-of-labels": {
				Default: &popularActionDefaultValue2,
			},
			"any-of-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"ascending": {
				Default: &popularActionDefaultValue6,
			},
			"close-issue-label":   {},
			"close-issue-message": {},
			"close-pr-label":      {},
			"close-pr-message":    {},
			"days-before-close": {
				Default: &popularActionDefaultValue36,
			},
			"days-before-issue-close": {},
			"days-before-issue-stale": {},
			"days-before-pr-close":    {},
			"days-before-pr-stale":    {},
			"days-before-stale": {
				Default: &popularActionDefaultValue37,
			},
			"debug-only": {
				Default: &popularActionDefaultValue6,
			},
			"delete-branch": {
				Default: &popularActionDefaultValue6,
			},
			"enable-statistics": {
				Default: &popularActionDefaultValue4,
			},
			"exempt-all-assignees": {
				Default: &popularActionDefaultValue6,
			},
			"exempt-all-issue-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-issue-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-milestones": {
				Default: &popularActionDefaultValue6,
			},
			"exempt-all-pr-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-pr-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"only-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"only-labels": {
				Default: &popularActionDefaultValue2,
			},
			"only-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"operations-per-run": {
				Default: &popularActionDefaultValue38,
			},
			"remove-issue-stale-when-updated": {
				Default: &popularActionDefaultValue4,
			},
			"remove-pr-stale-when-updated": {
				Default: &popularActionDefaultValue4,
			},
			"remove-stale-when-updated": {
				Default: &popularActionDefaultValue4,
			},
			"repo-token": {
				Default: &popularActionDefaultValue3,
			},
			"skip-stale-issue-message": {
				Default: &popularActionDefaultValue6,
			},
			"skip-stale-pr-message": {
				Default: &popularActionDefaultValue6,
			},
			"stale-issue-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-pr-message": {},
			"start-date": {
				Default: &popularActionDefaultValue2,
			},
		},
	},
	"actions/stale@v4": {
		Name: "Close Stale Issues",
		Inputs: map[string]*ActionMetadataInput{
			"any-of-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"any-of-labels": {
				Default: &popularActionDefaultValue2,
			},
			"any-of-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"ascending": {
				Default: &popularActionDefaultValue6,
			},
			"close-issue-label":   {},
			"close-issue-message": {},
			"close-pr-label":      {},
			"close-pr-message":    {},
			"days-before-close": {
				Default: &popularActionDefaultValue36,
			},
			"days-before-issue-close": {},
			"days-before-issue-stale": {},
			"days-before-pr-close":    {},
			"days-before-pr-stale":    {},
			"days-before-stale": {
				Default: &popularActionDefaultValue37,
			},
			"debug-only": {
				Default: &popularActionDefaultValue6,
			},
			"delete-branch": {
				Default: &popularActionDefaultValue6,
			},
			"enable-statistics": {
				Default: &popularActionDefaultValue4,
			},
			"exempt-all-assignees": {
				Default: &popularActionDefaultValue6,
			},
			"exempt-all-issue-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-issue-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-milestones": {
				Default: &popularActionDefaultValue6,
			},
			"exempt-all-pr-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-all-pr-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-issue-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-assignees": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"exempt-pr-milestones": {
				Default: &popularActionDefaultValue2,
			},
			"only-issue-labels": {
				Default: &popularActionDefaultValue2,
			},
			"only-labels": {
				Default: &popularActionDefaultValue2,
			},
			"only-pr-labels": {
				Default: &popularActionDefaultValue2,
			},
			"operations-per-run": {
				Default: &popularActionDefaultValue38,
			},
			"remove-issue-stale-when-updated": {
				Default: &popularActionDefaultValue2,
			},
			"remove-pr-stale-when-updated": {
				Default: &popularActionDefaultValue2,
			},
			"remove-stale-when-updated": {
				Default: &popularActionDefaultValue4,
			},
			"repo-token": {
				Default: &popularActionDefaultValue3,
			},
			"stale-issue-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-issue-message": {},
			"stale-pr-label": {
				Default: &popularActionDefaultValue39,
			},
			"stale-pr-message": {},
			"start-date": {
				Default: &popularActionDefaultValue2,
			},
		},
		Outputs: map[string]struct{}{
			"closed-issues-prs": {},
			"staled-issues-prs": {},
		},
	},
	"actions/upload-artifact@v1": {
		Name: "Upload a Build Artifact",
		Inputs: map[string]*ActionMetadataInput{
			"name": {
				Required: true,
			},
			"path": {
				Required: true,
			},
		},
	},
	"actions/upload-artifact@v2": {
		Name: "Upload a Build Artifact",
		Inputs: map[string]*ActionMetadataInput{
			"if-no-files-found": {
				Default: &popularActionDefaultValue40,
			},
			"name": {
				Default: &popularActionDefaultValue41,
			},
			"path": {
				Required: true,
			},
			"retention-days": {},
		},
	},
	"aws-actions/configure-aws-credentials@v1": {
		Name: "\"Configure AWS Credentials\" Action For GitHub Actions",
		Inputs: map[string]*ActionMetadataInput{
			"aws-access-key-id": {},
			"aws-region": {
				Required: true,
			},
			"aws-secret-access-key":     {},
			"aws-session-token":         {},
			"mask-aws-account-id":       {},
			"role-duration-seconds":     {},
			"role-external-id":          {},
			"role-session-name":         {},
			"role-skip-session-tagging": {},
			"role-to-assume":            {},
		},
		Outputs: map[string]struct{}{
			"aws-account-id": {},
		},
	},
	"azure/aks-set-context@v1": {
		Name: "Azure Kubernetes set context",
		Inputs: map[string]*ActionMetadataInput{
			"cluster-name": {
				Default: &popularActionDefaultValue2,
			},
			"creds": {
				Required: true,
				Default:  &popularActionDefaultValue2,
			},
			"resource-group": {
				Default: &popularActionDefaultValue2,
			},
		},
	},
	"azure/login@v1": {
		Name: "Azure Login",
		Inputs: map[string]*ActionMetadataInput{
			"allow-no-subscriptions": {
				Default: &popularActionDefaultValue6,
			},
			"creds": {
				Required: true,
			},
			"enable-AzPSSession": {
				Default: &popularActionDefaultValue6,
			},
			"environment": {
				Default: &popularActionDefaultValue42,
			},
		},
	},
	"bahmutov/npm-install@v1": {
		Name: "NPM or Yarn install with caching",
		Inputs: map[string]*ActionMetadataInput{
			"install-command":   {},
			"useLockFile":       {},
			"useRollingCache":   {},
			"working-directory": {},
		},
	},
	"codecov/codecov-action@v1": {
		Name: "Codecov",
		Inputs: map[string]*ActionMetadataInput{
			"aws_curl_args":          {},
			"codecov_curl_args":      {},
			"commit_parent":          {},
			"directory":              {},
			"env_vars":               {},
			"fail_ci_if_error":       {},
			"file":                   {},
			"files":                  {},
			"flags":                  {},
			"functionalities":        {},
			"gcov_args":              {},
			"gcov_executable":        {},
			"gcov_path_exclude":      {},
			"gcov_path_include":      {},
			"gcov_prefix":            {},
			"gcov_root_dir":          {},
			"move_coverage_to_trash": {},
			"name":                   {},
			"network_filter":         {},
			"override_branch":        {},
			"override_build":         {},
			"override_commit":        {},
			"override_pr":            {},
			"override_tag":           {},
			"path_to_write_report":   {},
			"root_dir":               {},
			"token":                  {},
			"verbose":                {},
			"working-directory":      {},
			"xcode_derived_data":     {},
			"xcode_package":          {},
		},
	},
	"codecov/codecov-action@v2": {
		Name: "Codecov",
		Inputs: map[string]*ActionMetadataInput{
			"commit_parent":          {},
			"directory":              {},
			"dry_run":                {},
			"env_vars":               {},
			"fail_ci_if_error":       {},
			"file":                   {},
			"files":                  {},
			"flags":                  {},
			"functionalities":        {},
			"move_coverage_to_trash": {},
			"name":                   {},
			"override_branch":        {},
			"override_build":         {},
			"override_commit":        {},
			"override_pr":            {},
			"override_tag":           {},
			"root_dir":               {},
			"slug":                   {},
			"token":                  {},
			"url":                    {},
			"verbose":                {},
			"working-directory":      {},
		},
	},
	"dawidd6/action-download-artifact@v2": {
		Name: "Download workflow artifact",
		Inputs: map[string]*ActionMetadataInput{
			"branch": {},
			"commit": {},
			"event":  {},
			"github_token": {
				Default: &popularActionDefaultValue43,
			},
			"name": {},
			"path": {
				Default: &popularActionDefaultValue44,
			},
			"pr": {},
			"repo": {
				Default: &popularActionDefaultValue45,
			},
			"run_id":     {},
			"run_number": {},
			"workflow": {
				Required: true,
			},
			"workflow_conclusion": {
				Default: &popularActionDefaultValue46,
			},
		},
	},
	"dawidd6/action-send-mail@v1": {
		Name: "Send email",
		Inputs: map[string]*ActionMetadataInput{
			"body": {
				Required: true,
			},
			"content_type": {
				Default: &popularActionDefaultValue47,
			},
			"from": {
				Required: true,
			},
			"password": {
				Required: true,
			},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {
				Required: true,
			},
		},
	},
	"dawidd6/action-send-mail@v2": {
		Name: "Send email",
		Inputs: map[string]*ActionMetadataInput{
			"attachments": {},
			"bcc":         {},
			"body": {
				Required: true,
			},
			"cc": {},
			"content_type": {
				Default: &popularActionDefaultValue47,
			},
			"convert_markdown": {},
			"from": {
				Required: true,
			},
			"ignore_cert": {},
			"password": {
				Required: true,
			},
			"reply_to": {},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {
				Required: true,
			},
		},
	},
	"dawidd6/action-send-mail@v3": {
		Name: "Send email",
		Inputs: map[string]*ActionMetadataInput{
			"attachments":      {},
			"bcc":              {},
			"body":             {},
			"cc":               {},
			"convert_markdown": {},
			"from": {
				Required: true,
			},
			"html_body":   {},
			"ignore_cert": {},
			"password":    {},
			"priority":    {},
			"reply_to":    {},
			"secure":      {},
			"server_address": {
				Required: true,
			},
			"server_port": {
				Required: true,
			},
			"subject": {
				Required: true,
			},
			"to": {
				Required: true,
			},
			"username": {},
		},
	},
	"dessant/lock-threads@v2": {
		Name: "Lock Threads",
		Inputs: map[string]*ActionMetadataInput{
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"issue-exclude-created-before": {
				Default: &popularActionDefaultValue2,
			},
			"issue-exclude-labels": {
				Default: &popularActionDefaultValue2,
			},
			"issue-lock-comment": {
				Default: &popularActionDefaultValue2,
			},
			"issue-lock-inactive-days": {
				Default: &popularActionDefaultValue48,
			},
			"issue-lock-labels": {
				Default: &popularActionDefaultValue2,
			},
			"issue-lock-reason": {
				Default: &popularActionDefaultValue49,
			},
			"pr-exclude-created-before": {
				Default: &popularActionDefaultValue2,
			},
			"pr-exclude-labels": {
				Default: &popularActionDefaultValue2,
			},
			"pr-lock-comment": {
				Default: &popularActionDefaultValue2,
			},
			"pr-lock-inactive-days": {
				Default: &popularActionDefaultValue48,
			},
			"pr-lock-labels": {
				Default: &popularActionDefaultValue2,
			},
			"pr-lock-reason": {
				Default: &popularActionDefaultValue49,
			},
			"process-only": {
				Default: &popularActionDefaultValue2,
			},
		},
		Outputs: map[string]struct{}{
			"issues": {},
			"prs":    {},
		},
	},
	"docker/build-push-action@v1": {
		Name: "Build and push Docker images",
		Inputs: map[string]*ActionMetadataInput{
			"add_git_labels": {
				Default: &popularActionDefaultValue6,
			},
			"always_pull": {
				Default: &popularActionDefaultValue6,
			},
			"build_args":  {},
			"cache_froms": {},
			"dockerfile":  {},
			"labels":      {},
			"password":    {},
			"path": {
				Default: &popularActionDefaultValue7,
			},
			"push": {
				Default: &popularActionDefaultValue4,
			},
			"registry": {},
			"repository": {
				Required: true,
			},
			"tag_with_ref": {
				Default: &popularActionDefaultValue6,
			},
			"tag_with_sha": {
				Default: &popularActionDefaultValue6,
			},
			"tags":     {},
			"target":   {},
			"username": {},
		},
	},
	"docker/build-push-action@v2": {
		Name: "Build and push Docker images",
		Inputs: map[string]*ActionMetadataInput{
			"allow":      {},
			"build-args": {},
			"builder":    {},
			"cache-from": {},
			"cache-to":   {},
			"context":    {},
			"file":       {},
			"github-token": {
				Default: &popularActionDefaultValue3,
			},
			"labels": {},
			"load": {
				Default: &popularActionDefaultValue6,
			},
			"network": {},
			"no-cache": {
				Default: &popularActionDefaultValue6,
			},
			"outputs":   {},
			"platforms": {},
			"pull": {
				Default: &popularActionDefaultValue6,
			},
			"push": {
				Default: &popularActionDefaultValue6,
			},
			"secret-files": {},
			"secrets":      {},
			"ssh":          {},
			"tags":         {},
			"target":       {},
		},
		Outputs: map[string]struct{}{
			"digest": {},
		},
	},
	"docker/login-action@v1": {
		Name: "Docker Login",
		Inputs: map[string]*ActionMetadataInput{
			"logout": {
				Default: &popularActionDefaultValue4,
			},
			"password": {},
			"registry": {},
			"username": {},
		},
	},
	"docker/metadata-action@v1": {
		Name: "Docker Meta",
		Inputs: map[string]*ActionMetadataInput{
			"github-token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"images": {
				Required: true,
			},
			"label-custom":    {},
			"sep-labels":      {},
			"sep-tags":        {},
			"tag-custom":      {},
			"tag-custom-only": {},
			"tag-edge": {
				Default: &popularActionDefaultValue6,
			},
			"tag-edge-branch": {},
			"tag-latest": {
				Default: &popularActionDefaultValue4,
			},
			"tag-match": {},
			"tag-match-group": {
				Default: &popularActionDefaultValue50,
			},
			"tag-match-latest": {
				Default: &popularActionDefaultValue4,
			},
			"tag-schedule": {
				Default: &popularActionDefaultValue51,
			},
			"tag-semver": {},
			"tag-sha": {
				Default: &popularActionDefaultValue6,
			},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/metadata-action@v2": {
		Name: "Docker Meta",
		Inputs: map[string]*ActionMetadataInput{
			"bake-target": {},
			"flavor":      {},
			"github-token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"images": {
				Required: true,
			},
			"labels":     {},
			"sep-labels": {},
			"sep-tags":   {},
			"tags":       {},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/metadata-action@v3": {
		Name: "Docker Metadata action",
		Inputs: map[string]*ActionMetadataInput{
			"bake-target": {},
			"flavor":      {},
			"github-token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"images": {
				Required: true,
			},
			"labels":     {},
			"sep-labels": {},
			"sep-tags":   {},
			"tags":       {},
		},
		Outputs: map[string]struct{}{
			"bake-file": {},
			"labels":    {},
			"tags":      {},
			"version":   {},
		},
	},
	"docker/setup-buildx-action@v1": {
		Name: "Docker Setup Buildx",
		Inputs: map[string]*ActionMetadataInput{
			"buildkitd-flags": {
				Default: &popularActionDefaultValue52,
			},
			"config": {},
			"driver": {
				Default: &popularActionDefaultValue53,
			},
			"driver-opts": {},
			"endpoint":    {},
			"install": {
				Default: &popularActionDefaultValue6,
			},
			"use": {
				Default: &popularActionDefaultValue4,
			},
			"version": {},
		},
		Outputs: map[string]struct{}{
			"driver":    {},
			"endpoint":  {},
			"flags":     {},
			"name":      {},
			"platforms": {},
			"status":    {},
		},
	},
	"docker/setup-qemu-action@v1": {
		Name: "Docker Setup QEMU",
		Inputs: map[string]*ActionMetadataInput{
			"image": {
				Default: &popularActionDefaultValue54,
			},
			"platforms": {
				Default: &popularActionDefaultValue55,
			},
		},
		Outputs: map[string]struct{}{
			"platforms": {},
		},
	},
	"dorny/paths-filter@v1": {
		Name: "Pull request changed files filter",
		Inputs: map[string]*ActionMetadataInput{
			"filters": {
				Required: true,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		SkipOutputs: true,
	},
	"dorny/paths-filter@v2": {
		Name: "Paths Changes Filter",
		Inputs: map[string]*ActionMetadataInput{
			"base": {},
			"filters": {
				Required: true,
			},
			"initial-fetch-depth": {
				Default: &popularActionDefaultValue56,
			},
			"list-files": {
				Required: true,
				Default:  &popularActionDefaultValue57,
			},
			"ref": {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"working-directory": {},
		},
		SkipOutputs: true,
	},
	"enriikke/gatsby-gh-pages-action@v2": {
		Name: "Gatsby Publish",
		Inputs: map[string]*ActionMetadataInput{
			"access-token": {
				Required: true,
			},
			"commit-message": {
				Default: &popularActionDefaultValue2,
			},
			"deploy-branch": {
				Default: &popularActionDefaultValue58,
			},
			"deploy-repo": {
				Default: &popularActionDefaultValue2,
			},
			"gatsby-args": {
				Default: &popularActionDefaultValue2,
			},
			"git-config-email": {
				Default: &popularActionDefaultValue2,
			},
			"git-config-name": {
				Default: &popularActionDefaultValue2,
			},
			"skip-publish": {
				Default: &popularActionDefaultValue6,
			},
			"working-dir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"erlef/setup-beam@v1": {
		Name: "Setup Erlang/OTP with optional Elixir (and mix) and/or rebar3",
		Inputs: map[string]*ActionMetadataInput{
			"elixir-version": {},
			"install-hex": {
				Default: &popularActionDefaultValue4,
			},
			"install-rebar": {
				Default: &popularActionDefaultValue4,
			},
			"otp-version":    {},
			"rebar3-version": {},
			"version-type": {
				Default: &popularActionDefaultValue59,
			},
		},
		Outputs: map[string]struct{}{
			"elixir-version": {},
			"otp-version":    {},
			"rebar3-version": {},
		},
	},
	"game-ci/unity-builder@v2": {
		Name: "Unity - Builder",
		Inputs: map[string]*ActionMetadataInput{
			"allowDirtyBuild": {
				Default: &popularActionDefaultValue2,
			},
			"androidAppBundle": {
				Default: &popularActionDefaultValue6,
			},
			"androidKeyaliasName": {
				Default: &popularActionDefaultValue2,
			},
			"androidKeyaliasPass": {
				Default: &popularActionDefaultValue2,
			},
			"androidKeystoreBase64": {
				Default: &popularActionDefaultValue2,
			},
			"androidKeystoreName": {
				Default: &popularActionDefaultValue2,
			},
			"androidKeystorePass": {
				Default: &popularActionDefaultValue2,
			},
			"androidVersionCode": {
				Default: &popularActionDefaultValue2,
			},
			"awsStackName": {
				Default: &popularActionDefaultValue60,
			},
			"buildMethod": {
				Default: &popularActionDefaultValue2,
			},
			"buildName": {
				Default: &popularActionDefaultValue2,
			},
			"buildsPath": {
				Default: &popularActionDefaultValue2,
			},
			"chownFilesTo": {
				Default: &popularActionDefaultValue2,
			},
			"customImage": {
				Default: &popularActionDefaultValue2,
			},
			"customParameters": {
				Default: &popularActionDefaultValue2,
			},
			"githubToken": {
				Default: &popularActionDefaultValue2,
			},
			"kubeConfig": {
				Default: &popularActionDefaultValue2,
			},
			"kubeVolume": {
				Default: &popularActionDefaultValue2,
			},
			"kubeVolumeSize": {
				Default: &popularActionDefaultValue61,
			},
			"projectPath": {
				Default: &popularActionDefaultValue2,
			},
			"remoteBuildCluster": {
				Default: &popularActionDefaultValue62,
			},
			"remoteBuildCpu": {
				Default: &popularActionDefaultValue15,
			},
			"remoteBuildMemory": {
				Default: &popularActionDefaultValue63,
			},
			"sshAgent": {
				Default: &popularActionDefaultValue2,
			},
			"targetPlatform": {
				Default: &popularActionDefaultValue2,
			},
			"unityVersion": {
				Default: &popularActionDefaultValue64,
			},
			"version": {
				Default: &popularActionDefaultValue2,
			},
			"versioning": {
				Default: &popularActionDefaultValue65,
			},
		},
		Outputs: map[string]struct{}{
			"buildVersion": {},
			"volume":       {},
		},
	},
	"getsentry/paths-filter@v1": {
		Name: "Pull request changed files filter",
		Inputs: map[string]*ActionMetadataInput{
			"filters": {
				Required: true,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		SkipOutputs: true,
	},
	"getsentry/paths-filter@v2": {
		Name: "Paths Changes Filter",
		Inputs: map[string]*ActionMetadataInput{
			"base": {},
			"filters": {
				Required: true,
			},
			"initial-fetch-depth": {
				Default: &popularActionDefaultValue56,
			},
			"list-files": {
				Required: true,
				Default:  &popularActionDefaultValue57,
			},
			"ref": {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"working-directory": {},
		},
		SkipOutputs: true,
	},
	"github/codeql-action/analyze@v1": {
		Name: "CodeQL: Finish",
		Inputs: map[string]*ActionMetadataInput{
			"add-snippets": {
				Default: &popularActionDefaultValue6,
			},
			"category":   {},
			"check_name": {},
			"checkout_path": {
				Default: &popularActionDefaultValue66,
			},
			"cleanup-level": {
				Default: &popularActionDefaultValue67,
			},
			"matrix": {
				Default: &popularActionDefaultValue68,
			},
			"output": {
				Default: &popularActionDefaultValue69,
			},
			"ram": {},
			"skip-queries": {
				Default: &popularActionDefaultValue6,
			},
			"threads": {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"upload": {
				Default: &popularActionDefaultValue4,
			},
			"upload-database": {
				Default: &popularActionDefaultValue4,
			},
		},
		Outputs: map[string]struct{}{
			"db-locations": {},
		},
	},
	"github/codeql-action/autobuild@v1": {
		Name: "CodeQL: Autobuild",
		Inputs: map[string]*ActionMetadataInput{
			"matrix": {
				Default: &popularActionDefaultValue68,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
	},
	"github/codeql-action/init@v1": {
		Name: "CodeQL: Init",
		Inputs: map[string]*ActionMetadataInput{
			"config-file":               {},
			"db-location":               {},
			"external-repository-token": {},
			"languages":                 {},
			"matrix": {
				Default: &popularActionDefaultValue68,
			},
			"packs":   {},
			"queries": {},
			"setup-python-dependencies": {
				Required: true,
				Default:  &popularActionDefaultValue4,
			},
			"source-root": {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"tools": {},
		},
		Outputs: map[string]struct{}{
			"codeql-path": {},
		},
	},
	"github/super-linter@v3": {
		Name: "Super-Linter",
	},
	"github/super-linter@v4": {
		Name: "Super-Linter",
	},
	"githubocto/flat@v1": {
		Name: "Flat Data",
		Inputs: map[string]*ActionMetadataInput{
			"http_url": {},
			"outfile_basename": {
				Default: &popularActionDefaultValue70,
			},
			"postprocess":    {},
			"sql_connstring": {},
			"sql_format": {
				Default: &popularActionDefaultValue25,
			},
			"sql_queryfile": {
				Default: &popularActionDefaultValue71,
			},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"githubocto/flat@v2": {
		Name: "Flat Data",
		Inputs: map[string]*ActionMetadataInput{
			"downloaded_filename": {},
			"http_url":            {},
			"postprocess":         {},
			"sql_connstring":      {},
			"sql_queryfile": {
				Default: &popularActionDefaultValue71,
			},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"githubocto/flat@v3": {
		Name: "Flat Data",
		Inputs: map[string]*ActionMetadataInput{
			"authorization":       {},
			"axios_config":        {},
			"downloaded_filename": {},
			"http_url":            {},
			"mask":                {},
			"postprocess":         {},
			"sql_connstring":      {},
			"sql_queryfile": {
				Default: &popularActionDefaultValue71,
			},
			"typeorm_config": {},
		},
		Outputs: map[string]struct{}{
			"delta_bytes": {},
		},
	},
	"golangci/golangci-lint-action@v1": {
		Name: "Run golangci-lint",
		Inputs: map[string]*ActionMetadataInput{
			"args": {
				Default: &popularActionDefaultValue2,
			},
			"github-token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"only-new-issues": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"version": {
				Required: true,
			},
			"working-directory": {},
		},
	},
	"golangci/golangci-lint-action@v2": {
		Name: "Run golangci-lint",
		Inputs: map[string]*ActionMetadataInput{
			"args": {
				Default: &popularActionDefaultValue2,
			},
			"github-token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"only-new-issues": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"skip-build-cache": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"skip-go-installation": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"skip-pkg-cache": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"version":           {},
			"working-directory": {},
		},
	},
	"goreleaser/goreleaser-action@v1": {
		Name: "GoReleaser Action",
		Inputs: map[string]*ActionMetadataInput{
			"args": {},
			"key":  {},
			"version": {
				Default: &popularActionDefaultValue72,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"goreleaser/goreleaser-action@v2": {
		Name: "GoReleaser Action",
		Inputs: map[string]*ActionMetadataInput{
			"args": {},
			"distribution": {
				Default: &popularActionDefaultValue73,
			},
			"install-only": {
				Default: &popularActionDefaultValue6,
			},
			"version": {
				Default: &popularActionDefaultValue72,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"gradle/wrapper-validation-action@v1": {
		Name: "Gradle Wrapper Validation",
		Inputs: map[string]*ActionMetadataInput{
			"allow-checksums": {
				Default: &popularActionDefaultValue2,
			},
			"allow-snapshots": {
				Default: &popularActionDefaultValue6,
			},
			"min-wrapper-count": {
				Default: &popularActionDefaultValue23,
			},
		},
	},
	"haskell/actions/setup@v1": {
		Name: "Setup Haskell",
		Inputs: map[string]*ActionMetadataInput{
			"cabal-version": {
				Default: &popularActionDefaultValue72,
			},
			"disable-matcher": {},
			"enable-stack":    {},
			"ghc-version": {
				Default: &popularActionDefaultValue72,
			},
			"stack-no-global": {},
			"stack-setup-ghc": {},
			"stack-version": {
				Default: &popularActionDefaultValue72,
			},
		},
		Outputs: map[string]struct{}{
			"cabal-exe":   {},
			"cabal-path":  {},
			"cabal-store": {},
			"ghc-exe":     {},
			"ghc-path":    {},
			"stack-exe":   {},
			"stack-path":  {},
			"stack-root":  {},
		},
	},
	"marvinpinto/action-automatic-releases@latest": {
		Name: "Automatic Releases",
		Inputs: map[string]*ActionMetadataInput{
			"automatic_release_tag": {},
			"draft": {
				Default: &popularActionDefaultValue6,
			},
			"files": {},
			"prerelease": {
				Default: &popularActionDefaultValue4,
			},
			"repo_token": {
				Required: true,
			},
			"title": {},
		},
		Outputs: map[string]struct{}{
			"automatic_releases_tag": {},
			"upload_url":             {},
		},
	},
	"microsoft/playwright-github-action@v1": {
		Name: "Run Playwright tests",
	},
	"mikepenz/release-changelog-builder-action@v1": {
		Name: "Release Changelog Builder",
		Inputs: map[string]*ActionMetadataInput{
			"commitMode": {
				Default: &popularActionDefaultValue6,
			},
			"configuration": {},
			"failOnError": {
				Default: &popularActionDefaultValue6,
			},
			"fromTag": {},
			"ignorePreReleases": {
				Default: &popularActionDefaultValue6,
			},
			"outputFile": {},
			"owner":      {},
			"path":       {},
			"repo":       {},
			"toTag":      {},
			"token":      {},
		},
		Outputs: map[string]struct{}{
			"changelog": {},
			"failed":    {},
			"fromTag":   {},
			"owner":     {},
			"repo":      {},
			"toTag":     {},
		},
	},
	"mikepenz/release-changelog-builder-action@v2": {
		Name: "Release Changelog Builder",
		Inputs: map[string]*ActionMetadataInput{
			"commitMode": {
				Default: &popularActionDefaultValue6,
			},
			"configuration": {},
			"failOnError": {
				Default: &popularActionDefaultValue6,
			},
			"fromTag": {},
			"ignorePreReleases": {
				Default: &popularActionDefaultValue6,
			},
			"outputFile": {},
			"owner":      {},
			"path":       {},
			"repo":       {},
			"toTag":      {},
			"token":      {},
		},
		Outputs: map[string]struct{}{
			"changelog": {},
			"failed":    {},
			"fromTag":   {},
			"owner":     {},
			"repo":      {},
			"toTag":     {},
		},
	},
	"msys2/setup-msys2@v1": {
		Name: "Setup MSYS2 environment",
		Inputs: map[string]*ActionMetadataInput{
			"cache": {
				Default: &popularActionDefaultValue6,
			},
			"install": {
				Default: &popularActionDefaultValue6,
			},
			"msystem": {
				Default: &popularActionDefaultValue74,
			},
			"path-type": {
				Default: &popularActionDefaultValue75,
			},
			"release": {
				Default: &popularActionDefaultValue4,
			},
			"update": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"msys2/setup-msys2@v2": {
		Name: "Setup MSYS2",
		Inputs: map[string]*ActionMetadataInput{
			"install": {
				Default: &popularActionDefaultValue6,
			},
			"msystem": {
				Default: &popularActionDefaultValue74,
			},
			"path-type": {
				Default: &popularActionDefaultValue76,
			},
			"release": {
				Default: &popularActionDefaultValue4,
			},
			"update": {
				Default: &popularActionDefaultValue6,
			},
		},
	},
	"ncipollo/release-action@v1": {
		Name: "Create Release",
		Inputs: map[string]*ActionMetadataInput{
			"allowUpdates": {
				Default: &popularActionDefaultValue2,
			},
			"artifact": {
				Default: &popularActionDefaultValue2,
			},
			"artifactContentType": {
				Default: &popularActionDefaultValue2,
			},
			"artifactErrorsFailBuild": {
				Default: &popularActionDefaultValue2,
			},
			"artifacts": {
				Default: &popularActionDefaultValue2,
			},
			"body": {
				Default: &popularActionDefaultValue2,
			},
			"bodyFile": {
				Default: &popularActionDefaultValue2,
			},
			"commit": {
				Default: &popularActionDefaultValue2,
			},
			"discussionCategory": {
				Default: &popularActionDefaultValue2,
			},
			"draft": {
				Default: &popularActionDefaultValue2,
			},
			"name": {
				Default: &popularActionDefaultValue2,
			},
			"omitBody": {
				Default: &popularActionDefaultValue6,
			},
			"omitBodyDuringUpdate": {
				Default: &popularActionDefaultValue6,
			},
			"omitName": {
				Default: &popularActionDefaultValue6,
			},
			"omitNameDuringUpdate": {
				Default: &popularActionDefaultValue6,
			},
			"omitPrereleaseDuringUpdate": {
				Default: &popularActionDefaultValue6,
			},
			"owner": {
				Default: &popularActionDefaultValue2,
			},
			"prerelease": {
				Default: &popularActionDefaultValue2,
			},
			"replacesArtifacts": {
				Default: &popularActionDefaultValue4,
			},
			"repo": {
				Default: &popularActionDefaultValue2,
			},
			"tag": {
				Default: &popularActionDefaultValue2,
			},
			"token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
		},
		Outputs: map[string]struct{}{
			"html_url":   {},
			"id":         {},
			"upload_url": {},
		},
	},
	"nwtgck/actions-netlify@v1": {
		Name: "Netlify Actions",
		Inputs: map[string]*ActionMetadataInput{
			"alias":                           {},
			"deploy-message":                  {},
			"enable-commit-comment":           {},
			"enable-commit-status":            {},
			"enable-pull-request-comment":     {},
			"fails-without-credentials":       {},
			"functions-dir":                   {},
			"github-deployment-description":   {},
			"github-deployment-environment":   {},
			"github-token":                    {},
			"netlify-config-path":             {},
			"overwrites-pull-request-comment": {},
			"production-branch":               {},
			"production-deploy":               {},
			"publish-dir": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"deploy-url": {},
		},
	},
	"octokit/request-action@v1.x": {
		Name:       "GitHub API Request",
		SkipInputs: true,
		Outputs: map[string]struct{}{
			"data":    {},
			"headers": {},
			"status":  {},
		},
	},
	"octokit/request-action@v2.x": {
		Name:       "GitHub API Request",
		SkipInputs: true,
		Outputs: map[string]struct{}{
			"data":    {},
			"headers": {},
			"status":  {},
		},
	},
	"peaceiris/actions-gh-pages@v2": {
		Name: "GitHub Pages action",
		Inputs: map[string]*ActionMetadataInput{
			"commitMessage": {},
			"emptyCommits": {
				Default: &popularActionDefaultValue4,
			},
			"forceOrphan": {
				Default: &popularActionDefaultValue6,
			},
			"keepFiles": {
				Default: &popularActionDefaultValue6,
			},
			"tagMessage": {},
			"tagName":    {},
			"tagOverwrite": {
				Default: &popularActionDefaultValue6,
			},
			"useremail": {},
			"username":  {},
		},
	},
	"peaceiris/actions-gh-pages@v3": {
		Name: "GitHub Pages action",
		Inputs: map[string]*ActionMetadataInput{
			"allow_empty_commit": {
				Default: &popularActionDefaultValue6,
			},
			"cname":          {},
			"commit_message": {},
			"deploy_key":     {},
			"destination_dir": {
				Default: &popularActionDefaultValue2,
			},
			"disable_nojekyll": {
				Default: &popularActionDefaultValue6,
			},
			"enable_jekyll": {
				Default: &popularActionDefaultValue6,
			},
			"exclude_assets": {
				Default: &popularActionDefaultValue77,
			},
			"external_repository": {},
			"force_orphan": {
				Default: &popularActionDefaultValue6,
			},
			"full_commit_message": {},
			"github_token":        {},
			"keep_files": {
				Default: &popularActionDefaultValue6,
			},
			"personal_token": {},
			"publish_branch": {
				Default: &popularActionDefaultValue78,
			},
			"publish_dir": {
				Default: &popularActionDefaultValue79,
			},
			"tag_message": {},
			"tag_name":    {},
			"user_email":  {},
			"user_name":   {},
		},
	},
	"peter-evans/create-pull-request@v1": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionMetadataInput{
			"assignees":       {},
			"author-email":    {},
			"author-name":     {},
			"base":            {},
			"body":            {},
			"branch":          {},
			"branch-suffix":   {},
			"commit-message":  {},
			"committer-email": {},
			"committer-name":  {},
			"labels":          {},
			"milestone":       {},
			"project":         {},
			"project-column":  {},
			"reviewers":       {},
			"team-reviewers":  {},
			"title":           {},
			"token": {
				Required: true,
			},
		},
		Outputs: map[string]struct{}{
			"pr_number": {},
		},
	},
	"peter-evans/create-pull-request@v2": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionMetadataInput{
			"assignees":      {},
			"author":         {},
			"base":           {},
			"body":           {},
			"branch":         {},
			"branch-suffix":  {},
			"commit-message": {},
			"committer":      {},
			"draft":          {},
			"labels":         {},
			"milestone":      {},
			"path":           {},
			"project":        {},
			"project-column": {},
			"request-to-parent": {
				Default: &popularActionDefaultValue6,
			},
			"reviewers":      {},
			"team-reviewers": {},
			"title":          {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		Outputs: map[string]struct{}{
			"pull-request-number": {},
		},
	},
	"peter-evans/create-pull-request@v3": {
		Name: "Create Pull Request",
		Inputs: map[string]*ActionMetadataInput{
			"assignees": {},
			"author": {
				Default: &popularActionDefaultValue80,
			},
			"base": {},
			"body": {
				Default: &popularActionDefaultValue81,
			},
			"branch": {
				Default: &popularActionDefaultValue82,
			},
			"branch-suffix": {},
			"commit-message": {
				Default: &popularActionDefaultValue83,
			},
			"committer": {
				Default: &popularActionDefaultValue84,
			},
			"delete-branch": {
				Default: &popularActionDefaultValue6,
			},
			"draft": {
				Default: &popularActionDefaultValue6,
			},
			"labels":       {},
			"milestone":    {},
			"path":         {},
			"push-to-fork": {},
			"reviewers":    {},
			"signoff": {
				Default: &popularActionDefaultValue6,
			},
			"team-reviewers": {},
			"title": {
				Default: &popularActionDefaultValue85,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		Outputs: map[string]struct{}{
			"pull-request-number": {},
		},
	},
	"preactjs/compressed-size-action@v1": {
		Name: "compressed-size-action",
		Inputs: map[string]*ActionMetadataInput{
			"build-script": {
				Default: &popularActionDefaultValue86,
			},
			"collapse-unchanged": {
				Default: &popularActionDefaultValue4,
			},
			"compression":    {},
			"omit-unchanged": {},
			"repo-token": {
				Required: true,
			},
			"show-total": {
				Default: &popularActionDefaultValue4,
			},
		},
	},
	"preactjs/compressed-size-action@v2": {
		Name: "compressed-size-action",
		Inputs: map[string]*ActionMetadataInput{
			"build-script": {
				Default: &popularActionDefaultValue86,
			},
			"clean-script": {},
			"collapse-unchanged": {
				Default: &popularActionDefaultValue4,
			},
			"compression": {},
			"cwd":         {},
			"exclude": {
				Default: &popularActionDefaultValue87,
			},
			"minimum-change-threshold": {
				Default: &popularActionDefaultValue23,
			},
			"omit-unchanged": {},
			"pattern": {
				Default: &popularActionDefaultValue88,
			},
			"repo-token": {
				Default: &popularActionDefaultValue3,
			},
			"show-total": {
				Default: &popularActionDefaultValue4,
			},
			"strip-hash": {},
			"use-check":  {},
		},
	},
	"reviewdog/action-actionlint@v1": {
		Name: "actionlint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"actionlint_flags": {
				Default: &popularActionDefaultValue2,
			},
			"fail_on_error": {
				Required: true,
				Default:  &popularActionDefaultValue6,
			},
			"filter_mode": {
				Required: true,
				Default:  &popularActionDefaultValue89,
			},
			"github_token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"level": {
				Required: true,
				Default:  &popularActionDefaultValue90,
			},
			"reporter": {
				Required: true,
				Default:  &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"tool_name": {
				Required: true,
				Default:  &popularActionDefaultValue92,
			},
		},
	},
	"reviewdog/action-eslint@v1": {
		Name: "Run eslint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"eslint_flags": {
				Default: &popularActionDefaultValue7,
			},
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue93,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"tool_name": {
				Default: &popularActionDefaultValue94,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"reviewdog/action-golangci-lint@v1": {
		Name: "Run golangci-lint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"golangci_lint_flags": {
				Default: &popularActionDefaultValue2,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"tool_name": {
				Default: &popularActionDefaultValue95,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"reviewdog/action-golangci-lint@v2": {
		Name: "Run golangci-lint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"cache": {
				Default: &popularActionDefaultValue4,
			},
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Required: true,
				Default:  &popularActionDefaultValue3,
			},
			"go_version": {
				Default: &popularActionDefaultValue96,
			},
			"golangci_lint_flags": {
				Default: &popularActionDefaultValue2,
			},
			"golangci_lint_version": {
				Default: &popularActionDefaultValue72,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"reviewdog_version": {
				Default: &popularActionDefaultValue72,
			},
			"tool_name": {
				Default: &popularActionDefaultValue95,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"reviewdog/action-hadolint@v1": {
		Name: "Run hadolint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"exclude": {
				Default: &popularActionDefaultValue2,
			},
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Default: &popularActionDefaultValue3,
			},
			"hadolint_flags": {
				Default: &popularActionDefaultValue2,
			},
			"hadolint_ignore": {
				Default: &popularActionDefaultValue2,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"tool_name": {
				Default: &popularActionDefaultValue97,
			},
		},
	},
	"reviewdog/action-misspell@v1": {
		Name: "Run misspell with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"exclude": {
				Default: &popularActionDefaultValue2,
			},
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Default: &popularActionDefaultValue3,
			},
			"ignore": {
				Default: &popularActionDefaultValue2,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"locale": {
				Default: &popularActionDefaultValue2,
			},
			"path": {
				Default: &popularActionDefaultValue7,
			},
			"pattern": {
				Default: &popularActionDefaultValue98,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
		},
	},
	"reviewdog/action-rubocop@v1": {
		Name: "Run rubocop with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Required: true,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"rubocop_extensions": {
				Default: &popularActionDefaultValue99,
			},
			"rubocop_flags": {
				Default: &popularActionDefaultValue2,
			},
			"rubocop_version": {},
			"tool_name": {
				Default: &popularActionDefaultValue100,
			},
			"workdir": {
				Default: &popularActionDefaultValue7,
			},
		},
	},
	"reviewdog/action-shellcheck@v1": {
		Name: "Run shellcheck with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"exclude": {},
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"github_token": {
				Default: &popularActionDefaultValue3,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"path": {
				Default: &popularActionDefaultValue7,
			},
			"pattern": {
				Default: &popularActionDefaultValue101,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"reviewdog_flags": {
				Default: &popularActionDefaultValue2,
			},
			"shellcheck_flags": {
				Default: &popularActionDefaultValue102,
			},
		},
	},
	"reviewdog/action-tflint@v1": {
		Name: "Run tflint with reviewdog",
		Inputs: map[string]*ActionMetadataInput{
			"fail_on_error": {
				Default: &popularActionDefaultValue6,
			},
			"filter_mode": {
				Default: &popularActionDefaultValue89,
			},
			"flags": {
				Default: &popularActionDefaultValue103,
			},
			"github_token": {
				Required: true,
			},
			"level": {
				Default: &popularActionDefaultValue90,
			},
			"reporter": {
				Default: &popularActionDefaultValue91,
			},
			"tflint_rulesets": {
				Default: &popularActionDefaultValue2,
			},
			"tflint_version": {
				Default: &popularActionDefaultValue72,
			},
			"working_directory": {
				Default: &popularActionDefaultValue7,
			},
		},
		Outputs: map[string]struct{}{
			"reviewdog-return-code": {},
			"tflint-return-code":    {},
		},
	},
	"rhysd/action-setup-vim@v1": {
		Name: "Setup Vim",
		Inputs: map[string]*ActionMetadataInput{
			"neovim": {
				Default: &popularActionDefaultValue6,
			},
			"token": {
				Default: &popularActionDefaultValue3,
			},
			"version": {
				Default: &popularActionDefaultValue104,
			},
		},
		Outputs: map[string]struct{}{
			"executable": {},
		},
	},
	"ridedott/merge-me-action@v1": {
		Name: "Merge me!",
		Inputs: map[string]*ActionMetadataInput{
			"GITHUB_LOGIN": {
				Default: &popularActionDefaultValue105,
			},
			"GITHUB_TOKEN": {
				Required: true,
			},
			"MERGE_METHOD": {
				Default: &popularActionDefaultValue106,
			},
			"PRESET": {},
		},
	},
	"ridedott/merge-me-action@v2": {
		Name: "Merge me!",
		Inputs: map[string]*ActionMetadataInput{
			"ENABLED_FOR_MANUAL_CHANGES": {
				Default: &popularActionDefaultValue6,
			},
			"ENABLE_GITHUB_API_PREVIEW": {
				Default: &popularActionDefaultValue6,
			},
			"GITHUB_LOGIN": {
				Default: &popularActionDefaultValue107,
			},
			"GITHUB_TOKEN": {
				Required: true,
			},
			"MAXIMUM_RETRIES": {
				Default: &popularActionDefaultValue108,
			},
			"MERGE_METHOD": {
				Default: &popularActionDefaultValue106,
			},
			"PRESET": {},
		},
	},
	"rtCamp/action-slack-notify@v2": {
		Name: "Slack Notify",
	},
	"ruby/setup-ruby@v1": {
		Name: "Setup Ruby, JRuby and TruffleRuby",
		Inputs: map[string]*ActionMetadataInput{
			"bundler": {
				Default: &popularActionDefaultValue18,
			},
			"bundler-cache": {
				Default: &popularActionDefaultValue6,
			},
			"cache-version": {
				Default: &popularActionDefaultValue50,
			},
			"ruby-version": {
				Default: &popularActionDefaultValue18,
			},
			"working-directory": {
				Default: &popularActionDefaultValue7,
			},
		},
		Outputs: map[string]struct{}{
			"ruby-prefix": {},
		},
	},
	"shivammathur/setup-php@v1": {
		Name: "Setup PHP Action",
		Inputs: map[string]*ActionMetadataInput{
			"coverage":       {},
			"extension-csv":  {},
			"extensions":     {},
			"ini-values":     {},
			"ini-values-csv": {},
			"pecl":           {},
			"php-version": {
				Required: true,
				Default:  &popularActionDefaultValue109,
			},
			"tools": {},
		},
	},
	"shivammathur/setup-php@v2": {
		Name: "Setup PHP Action",
		Inputs: map[string]*ActionMetadataInput{
			"coverage":   {},
			"extensions": {},
			"ini-values": {},
			"php-version": {
				Required: true,
				Default:  &popularActionDefaultValue110,
			},
			"tools": {},
		},
		Outputs: map[string]struct{}{
			"php-version": {},
		},
	},
	"softprops/action-gh-release@v1": {
		Name: "GH Release",
		Inputs: map[string]*ActionMetadataInput{
			"body":                     {},
			"body_path":                {},
			"discussion_category_name": {},
			"draft":                    {},
			"fail_on_unmatched_files":  {},
			"files":                    {},
			"name":                     {},
			"prerelease":               {},
			"repository":               {},
			"tag_name":                 {},
			"target_commitish":         {},
			"token": {
				Default: &popularActionDefaultValue3,
			},
		},
		Outputs: map[string]struct{}{
			"id":         {},
			"upload_url": {},
			"url":        {},
		},
	},
	"subosito/flutter-action@v1": {
		Name: "Flutter action",
		Inputs: map[string]*ActionMetadataInput{
			"channel": {
				Default: &popularActionDefaultValue104,
			},
			"flutter-version": {},
		},
	},
	"treosh/lighthouse-ci-action@v1": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionMetadataInput{
			"url":  {},
			"urls": {},
		},
		Outputs: map[string]struct{}{
			"resultsPath": {},
		},
	},
	"treosh/lighthouse-ci-action@v2": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionMetadataInput{
			"budgetPath": {},
			"configPath": {},
			"runs": {
				Default: &popularActionDefaultValue23,
			},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"resultsPath": {},
		},
	},
	"treosh/lighthouse-ci-action@v3": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionMetadataInput{
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"treosh/lighthouse-ci-action@v7": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionMetadataInput{
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"treosh/lighthouse-ci-action@v8": {
		Name: "Lighthouse CI Action",
		Inputs: map[string]*ActionMetadataInput{
			"artifactName": {
				Default: &popularActionDefaultValue111,
			},
			"basicAuthPassword":      {},
			"basicAuthUsername":      {},
			"budgetPath":             {},
			"configPath":             {},
			"runs":                   {},
			"serverBaseUrl":          {},
			"serverToken":            {},
			"temporaryPublicStorage": {},
			"uploadArtifacts":        {},
			"urls":                   {},
		},
		Outputs: map[string]struct{}{
			"assertionResults": {},
			"links":            {},
			"resultsPath":      {},
		},
	},
	"wearerequired/lint-action@v1": {
		Name: "Lint Action",
		Inputs: map[string]*ActionMetadataInput{
			"auto_fix": {
				Default: &popularActionDefaultValue6,
			},
			"black": {
				Default: &popularActionDefaultValue6,
			},
			"black_args": {
				Default: &popularActionDefaultValue2,
			},
			"black_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"black_dir": {},
			"black_extensions": {
				Default: &popularActionDefaultValue112,
			},
			"check_name": {
				Default: &popularActionDefaultValue113,
			},
			"commit_message": {
				Default: &popularActionDefaultValue114,
			},
			"continue_on_error": {
				Default: &popularActionDefaultValue4,
			},
			"eslint": {
				Default: &popularActionDefaultValue6,
			},
			"eslint_args": {
				Default: &popularActionDefaultValue2,
			},
			"eslint_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"eslint_dir": {},
			"eslint_extensions": {
				Default: &popularActionDefaultValue115,
			},
			"flake8": {
				Default: &popularActionDefaultValue6,
			},
			"flake8_args": {
				Default: &popularActionDefaultValue2,
			},
			"flake8_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"flake8_dir": {},
			"flake8_extensions": {
				Default: &popularActionDefaultValue112,
			},
			"git_email": {
				Default: &popularActionDefaultValue116,
			},
			"git_name": {
				Default: &popularActionDefaultValue117,
			},
			"github_token": {
				Default: &popularActionDefaultValue3,
			},
			"gofmt": {
				Default: &popularActionDefaultValue6,
			},
			"gofmt_args": {
				Default: &popularActionDefaultValue2,
			},
			"gofmt_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"gofmt_dir": {},
			"gofmt_extensions": {
				Default: &popularActionDefaultValue118,
			},
			"golint": {
				Default: &popularActionDefaultValue6,
			},
			"golint_args": {
				Default: &popularActionDefaultValue2,
			},
			"golint_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"golint_dir": {},
			"golint_extensions": {
				Default: &popularActionDefaultValue118,
			},
			"mypy": {
				Default: &popularActionDefaultValue6,
			},
			"mypy_args": {
				Default: &popularActionDefaultValue2,
			},
			"mypy_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"mypy_dir": {},
			"mypy_extensions": {
				Default: &popularActionDefaultValue112,
			},
			"neutral_check_on_warning": {
				Default: &popularActionDefaultValue6,
			},
			"oitnb": {
				Default: &popularActionDefaultValue6,
			},
			"oitnb_args": {
				Default: &popularActionDefaultValue2,
			},
			"oitnb_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"oitnb_dir": {},
			"oitnb_extensions": {
				Default: &popularActionDefaultValue112,
			},
			"php_codesniffer": {
				Default: &popularActionDefaultValue6,
			},
			"php_codesniffer_args": {
				Default: &popularActionDefaultValue2,
			},
			"php_codesniffer_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"php_codesniffer_dir": {},
			"php_codesniffer_extensions": {
				Default: &popularActionDefaultValue119,
			},
			"prettier": {
				Default: &popularActionDefaultValue6,
			},
			"prettier_args": {
				Default: &popularActionDefaultValue2,
			},
			"prettier_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"prettier_dir": {},
			"prettier_extensions": {
				Default: &popularActionDefaultValue120,
			},
			"rubocop": {
				Default: &popularActionDefaultValue6,
			},
			"rubocop_args": {
				Default: &popularActionDefaultValue2,
			},
			"rubocop_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"rubocop_dir": {},
			"rubocop_extensions": {
				Default: &popularActionDefaultValue121,
			},
			"stylelint": {
				Default: &popularActionDefaultValue6,
			},
			"stylelint_args": {
				Default: &popularActionDefaultValue2,
			},
			"stylelint_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"stylelint_dir": {},
			"stylelint_extensions": {
				Default: &popularActionDefaultValue122,
			},
			"swift_format_lockwood": {
				Default: &popularActionDefaultValue6,
			},
			"swift_format_lockwood_args": {
				Default: &popularActionDefaultValue2,
			},
			"swift_format_lockwood_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"swift_format_lockwood_dir": {},
			"swift_format_lockwood_extensions": {
				Default: &popularActionDefaultValue123,
			},
			"swift_format_official": {
				Default: &popularActionDefaultValue6,
			},
			"swift_format_official_args": {
				Default: &popularActionDefaultValue2,
			},
			"swift_format_official_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"swift_format_official_dir": {},
			"swift_format_official_extensions": {
				Default: &popularActionDefaultValue123,
			},
			"swiftformat": {
				Default: &popularActionDefaultValue6,
			},
			"swiftformat_args": {
				Default: &popularActionDefaultValue2,
			},
			"swiftformat_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"swiftformat_dir": {},
			"swiftformat_extensions": {
				Default: &popularActionDefaultValue123,
			},
			"swiftlint": {
				Default: &popularActionDefaultValue6,
			},
			"swiftlint_args": {
				Default: &popularActionDefaultValue2,
			},
			"swiftlint_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"swiftlint_dir": {},
			"swiftlint_extensions": {
				Default: &popularActionDefaultValue123,
			},
			"xo": {
				Default: &popularActionDefaultValue6,
			},
			"xo_args": {
				Default: &popularActionDefaultValue2,
			},
			"xo_command_prefix": {
				Default: &popularActionDefaultValue2,
			},
			"xo_dir": {},
			"xo_extensions": {
				Default: &popularActionDefaultValue115,
			},
		},
	},
}
var popularActionDefaultValue0 = "here"
var popularActionDefaultValue1 = "8398a7@action-slack"
var popularActionDefaultValue2 = ""
var popularActionDefaultValue3 = "${{ github.token }}"
var popularActionDefaultValue4 = "true"
var popularActionDefaultValue5 = "HIGH"
var popularActionDefaultValue6 = "false"
var popularActionDefaultValue7 = "."
var popularActionDefaultValue8 = "Unit Test Results"
var popularActionDefaultValue9 = "all tests, skipped tests"
var popularActionDefaultValue10 = "update last"
var popularActionDefaultValue11 = "test failures"
var popularActionDefaultValue12 = "10"
var popularActionDefaultValue13 = "all but latest"
var popularActionDefaultValue14 = "merge"
var popularActionDefaultValue15 = "0.25"
var popularActionDefaultValue16 = "2.0"
var popularActionDefaultValue17 = "x86"
var popularActionDefaultValue18 = "default"
var popularActionDefaultValue19 = "test"
var popularActionDefaultValue20 = "2"
var popularActionDefaultValue21 = "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
var popularActionDefaultValue22 = "clippy"
var popularActionDefaultValue23 = "1"
var popularActionDefaultValue24 = "${{ github.repository }}"
var popularActionDefaultValue25 = "json"
var popularActionDefaultValue26 = "actions/github-script"
var popularActionDefaultValue27 = ".github/labeler.yml"
var popularActionDefaultValue28 = "1.10"
var popularActionDefaultValue29 = "x64"
var popularActionDefaultValue30 = "jdk"
var popularActionDefaultValue31 = "github"
var popularActionDefaultValue32 = "GITHUB_TOKEN"
var popularActionDefaultValue33 = "GITHUB_ACTOR"
var popularActionDefaultValue34 = "10.x"
var popularActionDefaultValue35 = "3.x"
var popularActionDefaultValue36 = "7"
var popularActionDefaultValue37 = "60"
var popularActionDefaultValue38 = "30"
var popularActionDefaultValue39 = "Stale"
var popularActionDefaultValue40 = "warn"
var popularActionDefaultValue41 = "artifact"
var popularActionDefaultValue42 = "azurecloud"
var popularActionDefaultValue43 = "${{github.token}}"
var popularActionDefaultValue44 = "./"
var popularActionDefaultValue45 = "${{github.repository}}"
var popularActionDefaultValue46 = "success"
var popularActionDefaultValue47 = "text/plain"
var popularActionDefaultValue48 = "365"
var popularActionDefaultValue49 = "resolved"
var popularActionDefaultValue50 = "0"
var popularActionDefaultValue51 = "nightly"
var popularActionDefaultValue52 = "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host"
var popularActionDefaultValue53 = "docker-container"
var popularActionDefaultValue54 = "tonistiigi/binfmt:latest"
var popularActionDefaultValue55 = "all"
var popularActionDefaultValue56 = "100"
var popularActionDefaultValue57 = "none"
var popularActionDefaultValue58 = "master"
var popularActionDefaultValue59 = "loose"
var popularActionDefaultValue60 = "game-ci"
var popularActionDefaultValue61 = "5Gi"
var popularActionDefaultValue62 = "local"
var popularActionDefaultValue63 = "800M"
var popularActionDefaultValue64 = "auto"
var popularActionDefaultValue65 = "Semantic"
var popularActionDefaultValue66 = "${{ github.workspace }}"
var popularActionDefaultValue67 = "brutal"
var popularActionDefaultValue68 = "${{ toJson(matrix) }}"
var popularActionDefaultValue69 = "../results"
var popularActionDefaultValue70 = "data"
var popularActionDefaultValue71 = ".github/workflows/query.sql"
var popularActionDefaultValue72 = "latest"
var popularActionDefaultValue73 = "goreleaser"
var popularActionDefaultValue74 = "MINGW64"
var popularActionDefaultValue75 = "strict"
var popularActionDefaultValue76 = "minimal"
var popularActionDefaultValue77 = ".github"
var popularActionDefaultValue78 = "gh-pages"
var popularActionDefaultValue79 = "public"
var popularActionDefaultValue80 = "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
var popularActionDefaultValue81 = "Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action"
var popularActionDefaultValue82 = "create-pull-request/patch"
var popularActionDefaultValue83 = "[create-pull-request] automated change"
var popularActionDefaultValue84 = "GitHub <noreply@github.com>"
var popularActionDefaultValue85 = "Changes by create-pull-request action"
var popularActionDefaultValue86 = "build"
var popularActionDefaultValue87 = "{**/*.map,**/node_modules/**}"
var popularActionDefaultValue88 = "**/dist/**/*.js"
var popularActionDefaultValue89 = "added"
var popularActionDefaultValue90 = "error"
var popularActionDefaultValue91 = "github-pr-check"
var popularActionDefaultValue92 = "actionlint"
var popularActionDefaultValue93 = "github-pr-review"
var popularActionDefaultValue94 = "eslint"
var popularActionDefaultValue95 = "golangci"
var popularActionDefaultValue96 = "1.x"
var popularActionDefaultValue97 = "hadolint"
var popularActionDefaultValue98 = "*"
var popularActionDefaultValue99 = "rubocop-rails rubocop-performance rubocop-rspec rubocop-i18n rubocop-rake"
var popularActionDefaultValue100 = "rubocop"
var popularActionDefaultValue101 = "*.sh"
var popularActionDefaultValue102 = "--external-sources"
var popularActionDefaultValue103 = "--module"
var popularActionDefaultValue104 = "stable"
var popularActionDefaultValue105 = "dependabot-preview[bot]"
var popularActionDefaultValue106 = "SQUASH"
var popularActionDefaultValue107 = "dependabot"
var popularActionDefaultValue108 = "3"
var popularActionDefaultValue109 = "7.4"
var popularActionDefaultValue110 = "8.0"
var popularActionDefaultValue111 = "lighthouse-results"
var popularActionDefaultValue112 = "py"
var popularActionDefaultValue113 = "${linter}"
var popularActionDefaultValue114 = "Fix code style issues with ${linter}"
var popularActionDefaultValue115 = "js"
var popularActionDefaultValue116 = "lint-action@samuelmeuli.com"
var popularActionDefaultValue117 = "Lint Action"
var popularActionDefaultValue118 = "go"
var popularActionDefaultValue119 = "php"
var popularActionDefaultValue120 = "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml"
var popularActionDefaultValue121 = "rb"
var popularActionDefaultValue122 = "css,sass,scss"
var popularActionDefaultValue123 = "swift"
