# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/rhysd/actionlint#readme"
  version "1.7.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actionlint"
  manpage "man/actionlint.1"
  depends_on formula: [
      "shellcheck",
    ]

  on_macos do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz"
      sha256 "28e5de5a05fc558474f638323d736d822fff183d2d492f0aecb2b73cc44584f5"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz"
      sha256 "2693315b9093aeacb4ebd91a993fea54fc215057bf0da2659056b4bc033873db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz"
      sha256 "023070a287cd8cccd71515fedc843f1985bf96c436b7effaecce67290e7e0757"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz"
      sha256 "401942f9c24ed71e4fe71b76c7d638f66d8633575c4016efd2977ce7c28317d0"
    end
  end

  # No zap stanza required
end
