# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  version "1.7.12"

  on_macos do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz"
      sha256 "5b44c3bc2255115c9b69e30efc0fecdf498fdb63c5d58e17084fd5f16324c644"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz"
      sha256 "aba9ced2dee8d27fecca3dc7feb1a7f9a52caefa1eb46f3271ea66b6e0e6953f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz"
      sha256 "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz"
      sha256 "325e971b6ba9bfa504672e29be93c24981eeb1c07576d730e9f7c8805afff0c6"
    end
  end

  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/rhysd/actionlint#readme"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "shellcheck",
    ]

  binary "actionlint"
  manpage "man/actionlint.1"

  # No zap stanza required

end
