# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/rhysd/actionlint#readme"
  version "1.7.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actionlint"
  manpage "man/actionlint.1"
  depends_on formula: [
      "shellcheck",
    ]

  on_macos do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz"
      sha256 "16b85caf792b34bcc40f7437736c4347680da0a1b034353a85012debbd71a461"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz"
      sha256 "ffb1f6c429a51dc9f37af9d11f96c16bd52f54b713bf7f8bd92f7fce9fd4284a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz"
      sha256 "be92c2652ab7b6d08425428797ceabeb16e31a781c07bc388456b4e592f3e36a"
    end
    on_arm do
      url "https://github.com/rhysd/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz"
      sha256 "4c65dbb2d59b409cdd75d47ffa8fa32af8f0eee573ac510468dc2275c48bf07c"
    end
  end

  # No zap stanza required
end
