// Code generated by actionlint/scripts/generate-webhook-events. DO NOT EDIT.

package actionlint

// AllWebhookTypes is a table of all webhooks with their types. This variable was generated by
// script at ./scripts/generate-webhook-events based on
// https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
// The value is nil when the activity types cannot be determined from the document. For example
// repository_dispatch event can contain arbitrary types that are customized by user.
var AllWebhookTypes = map[string][]string{
	"check_run":           {"created", "rerequested", "completed", "requested_action"},
	"fork":                {},
	"repository_dispatch": nil,
}
