// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionMetadata{
	"rhysd/action-setup-vim@v1.2.7": {
		Name: "Setup Vim",
		Inputs: map[string]*ActionMetadataInput{
			"neovim": {
				Default: &popularActionDefaultValue0,
			},
			"token": {
				Default: &popularActionDefaultValue1,
			},
			"version": {
				Default: &popularActionDefaultValue2,
			},
		},
		Outputs: map[string]struct{}{
			"executable": {},
		},
	},
	"rhysd/changelog-from-release/action@v2.2.2": {
		Name: "Run changelog-from-release",
		Inputs: map[string]*ActionMetadataInput{
			"commit": {
				Default: &popularActionDefaultValue3,
			},
			"file": {
				Required: true,
			},
			"github_token": {
				Required: true,
			},
			"push": {
				Default: &popularActionDefaultValue3,
			},
			"version": {},
		},
	},
}
var popularActionDefaultValue0 = "false"
var popularActionDefaultValue1 = "${{ github.token }}"
var popularActionDefaultValue2 = "stable"
var popularActionDefaultValue3 = "true"
