// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionMetadata{
	"rhysd/action-setup-vim@v1.2.7": {
		Name: "Setup Vim",
		Inputs: map[string]ActionMetadataInputRequired{
			"neovim":  false,
			"token":   false,
			"version": false,
		},
		Outputs: map[string]struct{}{
			"executable": {},
		},
	},
	"rhysd/changelog-from-release/action@v2.2.2": {
		Name: "Run changelog-from-release",
		Inputs: map[string]ActionMetadataInputRequired{
			"commit":       false,
			"file":         true,
			"github_token": true,
			"push":         false,
			"version":      false,
		},
	},
}
