// Code generated by actionlint/scripts/generate-popular-actions. DO NOT EDIT.

package actionlint

// PopularActions is data set of known popular actions. Keys are specs (owner/repo@ref) of actions
// and values are their metadata.
var PopularActions = map[string]*ActionMetadata{
	"rhysd/action-setup-vim@v1": {
		Name: "Setup Vim",
		Inputs: ActionMetadataInputs{
			"neovim":  {"neovim", false},
			"token":   {"token", false},
			"version": {"version", false},
		},
		Outputs: ActionMetadataOutputs{
			"executable": {"executable"},
		},
	},
}
